# Generated by Django 6.0.8 on 2026-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_transfer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(choices=[('signup', 'Sign up'), ('login', 'Login'), ('verify_phone', 'Verify phone')], default='signup', max_length=20)),
                ('code_hash', models.CharField(max_length=64)),
                ('attempts', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'purpose', 'is_used'], name='otp_codes_identif_252568_idx')],
            },
        ),
    ]
