
 # Generated by Django 6.0.8 on 2026-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('new_order', 'New Order'), ('points_earned', 'Points Earned'), ('mission_completed', 'Mission Completed'), ('reward_redeemed', 'Reward Redeemed'), ('punch_card_completed', 'Punch Card Completed'), ('special_offer', 'Special Offer'), ('transfer_sent', 'Transfer Sent'), ('transfer_received', 'Transfer Received'), ('waiter_call', 'Waiter Call'), ('generic', 'General')], default='generic', max_length=30),
        ),
    ]
