# Generated by Django 6.0.6 on 2026-07-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_remove_merchantprofile_listing_card_bg_and_more'),
        ('orders', '0015_add_guest_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preparation_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requires_preparation',
            field=models.BooleanField(default=True, help_text='Snapshot: whether this item requires preparation'),
        ),
        migrations.CreateModel(
            name='PreparationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Fallback area for unassigned menu items')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(blank=True, default='', help_text='Optional display color (hex or name)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_areas', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'preparation_areas',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.preparationarea'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['preparation_area', 'preparation_status'], name='order_items_prepara_4fe55f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'requires_preparation'], name='order_items_order_i_3243a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='preparationarea',
            constraint=models.UniqueConstraint(fields=('merchant', 'name'), name='unique_area_name_per_merchant'),
        ),
    ]
