# Generated by Django 6.0.6 on 2026-08-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_preparation_ready_at_and_more'),
        ('pos', '0006_staffpreparationarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preparation_ready_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_preparation_items', to='pos.shiftworker'),
        ),
    ]
