# Generated by Django 6.0.6 on 2026-08-02 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderitem_preparation_ready_by'),
        ('pos', '0007_alter_posauditlog_action_staffshift_staffshiftarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='preparation_staff_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_items', to='pos.staffshift'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='preparation_started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_preparation_items', to='pos.shiftworker'),
        ),
    ]
