# Generated by Django 6.0.6 on 2026-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_transfer_code'),
        ('loyalty', '0021_pointtransaction_pt_merchant_customer_idx'),
        ('merchants', '0012_merchantprofile_ai_enabled_and_more'),
        ('orders', '0018_orderitem_preparation_staff_shift_and_more'),
        ('pos', '0007_alter_posauditlog_action_staffshift_staffshiftarea_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['merchant', '-created_at'], name='orders_merchant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['merchant', 'status', '-created_at'], name='orders_merchant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_customer_created_idx'),
        ),
    ]
