# Generated by Django 6.0.6 on 2026-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_orders_merchant_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_breakdown',
            field=models.JSONField(blank=True, default=list, help_text='Per-component tax breakdown stored at creation time, e.g. [{"name":"CGST","rate":9.0,"amount":45.00},{"name":"SGST","rate":9.0,"amount":45.00}]'),
        ),
    ]
