# Generated by Django 6.0.6 on 2026-08-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_add_tax_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency_code_snapshot',
            field=models.CharField(blank=True, default='', help_text='Currency code at time of order (e.g. NPR, INR)', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_symbol_snapshot',
            field=models.CharField(blank=True, default='', help_text='Currency symbol at time of order (e.g. Rs, ₹)', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_rate_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Combined tax rate at time of order', max_digits=5),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_type_snapshot',
            field=models.CharField(blank=True, default='', help_text='Tax type name at time of order (e.g. VAT, GST)', max_length=50),
        ),
    ]
