# Generated by Django 6.0.6 on 2026-08-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_currency_code_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('punch_card_redemption', 'Punch Card Redemption'), ('reward_redemption', 'Reward Redemption'), ('staff_comp', 'Staff Free / Comp')], db_index=True, default='regular', max_length=30),
        ),
    ]
