# Generated by Django 6.0.6 on 2026-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_transfer_code'),
        ('loyalty', '0023_alter_pointtransaction_transaction_type'),
        ('merchants', '0018_merchantprofile_pdf_menu_page_count'),
        ('orders', '0022_add_staff_comp_order_type'),
        ('pos', '0009_reporthistory'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('client_mutation_id__isnull', True), _negated=True), fields=('customer', 'merchant', 'client_mutation_id'), name='uniq_customer_merchant_mutation'),
        ),
    ]
