# Generated by Django 6.0.8 on 2026-09-21 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_uniq_customer_merchant_mutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='special_instructions',
            field=models.TextField(blank=True, default='', help_text='Per-line customer special requests (stored as an immutable snapshot).'),
        ),
        migrations.CreateModel(
            name='OrderItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('option_name', models.CharField(max_length=255)),
                ('kind', models.CharField(default='modifier', max_length=20)),
                ('price_effect', models.DecimalField(decimal_places=2, default=0, help_text='Absolute variant price or modifier price_delta applied to this line.', max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.orderitem')),
            ],
            options={
                'db_table': 'order_item_options',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
