# Generated by Django 6.0.8 on 2026-09-28 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_orderitem_special_instructions_orderitemoption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prices_include_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="pricing_locked_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set once the order is paid, completed, cancelled or refunded; pricing is frozen after.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pricing_version",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_components_snapshot",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Tax components applied, e.g. [{"name":"VAT","rate":"13"}]',
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_policy_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tax policy code applied (see orders.pricing.tax.POLICIES)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Order-level discounts allocated to this line.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="list_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Unit price before Today's Special; null on pre-v1 lines.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="refunded_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="refunded_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_class",
            field=models.CharField(default="standard", max_length=12),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="taxable_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="What the customer paid for this line (0 on pre-v1 lines).",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="OrderAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual_discount", "Manual discount"),
                            ("loyalty_reward", "Loyalty reward"),
                            ("punch_reward", "Punch-card reward"),
                            ("promotion", "Promotion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calc_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed amount"),
                        ],
                        max_length=12,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("label", models.CharField(blank=True, default="", max_length=120)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "eligible_item_ids",
                    models.JSONField(
                        blank=True,
                        help_text="OrderItem ids the adjustment applies to; null = whole order.",
                        null=True,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Where it came from, e.g. "pos_discount:12".',
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("removed", "Removed")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("eligible", models.BooleanField(default=True)),
                ("reason", models.JSONField(blank=True, null=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_adjustments",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrderAdjustmentAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="orders.orderadjustment",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_allocations",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "db_table": "order_adjustment_allocations",
            },
        ),
        migrations.CreateModel(
            name="OrderCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("service", "Service charge"),
                            ("delivery", "Delivery fee"),
                            ("packaging", "Packaging fee"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "calc_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed amount"),
                        ],
                        max_length=12,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("taxable", models.BooleanField(default=False)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_charges",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="orderadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("order",),
                name="one_active_order_adjustment_v1",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderadjustmentallocation",
            constraint=models.UniqueConstraint(
                fields=("adjustment", "order_item"), name="uniq_adjustment_line"
            ),
        ),
    ]
