# Generated by Django 6.0.8 on 2026-09-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_backfill_legacy_tax_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="is_promotion_reward",
            field=models.BooleanField(
                default=False,
                help_text="Added as an offer's free/reward item (still a real, priced line).",
            ),
        ),
        migrations.AddField(
            model_name="orderitemoption",
            name="option_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="MenuOption id at order time (for variant-targeted offers); null on older rows.",
                null=True,
            ),
        ),
    ]
