# Generated by Django 6.0.8 on 2026-09-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_offers_line_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="loyalty_spend_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Spend points per unit of currency this order earns on its eligible paid lines (0 = item points only). Null on orders created before it was recorded. See loyalty.earning.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
