# Generated by Django 6.0.8 on 2026-10-07 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_google_sub_user_phone_verified_otpcode"),
        ("merchants", "0028_default_table_area"),
        ("orders", "0029_order_loyalty_spend_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_bill",
            field=models.BooleanField(
                default=True,
                help_text="True if this order acts as the primary consolidated bill",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="parent_bill",
            field=models.ForeignKey(
                blank=True,
                help_text="Consolidated parent bill if this is an additional order in a session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_orders",
                to="orders.order",
            ),
        ),
        migrations.CreateModel(
            name="DiningSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "guest_session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client-generated UUID for guest session",
                        max_length=64,
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bill_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="The primary open bill / order consolidating this dining session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_as_bill",
                        to="orders.order",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dining_sessions",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dining_sessions",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dining_sessions",
                        to="merchants.merchanttable",
                    ),
                ),
            ],
            options={
                "db_table": "dining_sessions",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="dining_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Dining session this order belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.diningsession",
            ),
        ),
        migrations.CreateModel(
            name="KitchenOrderTicket",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "kot_number",
                    models.PositiveIntegerField(
                        db_index=True,
                        help_text="Sequential KOT number per merchant per day",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("preparing", "Preparing"),
                            ("ready", "Ready"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "table_name_snapshot",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "table_number_snapshot",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "customer_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "fulfillment_type_snapshot",
                    models.CharField(blank=True, default="dine_in", max_length=20),
                ),
                (
                    "items_data",
                    models.JSONField(
                        default=list,
                        help_text="Snapshot of items in this KOT ticket for printing",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "dining_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kots",
                        to="orders.diningsession",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_order_tickets",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The bill order or specific order this ticket belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kots",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "kitchen_order_tickets",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="kot",
            field=models.ForeignKey(
                blank=True,
                help_text="Kitchen order ticket this item was submitted under",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="orders.kitchenorderticket",
            ),
        ),
        migrations.AddIndex(
            model_name="diningsession",
            index=models.Index(
                fields=["merchant", "table", "status"], name="dining_sess_m_t_s_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kitchenorderticket",
            index=models.Index(
                fields=["merchant", "-created_at"], name="kot_merchant_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kitchenorderticket",
            index=models.Index(
                fields=["order", "kot_number"], name="kot_order_number_idx"
            ),
        ),
    ]
