# Generated by Django 6.0.8 on 2026-10-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_order_is_bill_order_parent_bill_diningsession_and_more"),
        ("pos", "0017_alter_posauditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="complimentary_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee who gave the item free.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complimentary_items",
                to="pos.shiftworker",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="complimentary_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="What this line would have cost if it had been charged.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_complimentary",
            field=models.BooleanField(
                default=False,
                help_text="Given free by staff: charged 0, earns no loyalty.",
            ),
        ),
    ]
