# Generated by Django 6.0.6 on 2026-07-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0009_add_listing_card_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantprofile',
            name='listing_card_bg',
        ),
        migrations.RemoveField(
            model_name='merchantprofile',
            name='listing_card_text_color',
        ),
    ]
