# Generated by Django 6.0.6 on 2026-07-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_remove_merchantprofile_listing_card_bg_and_more'),
        ('orders', '0016_orderitem_preparation_ready_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='preparation_area',
            field=models.ForeignKey(blank=True, help_text='Specific preparation area for this item (overrides category default)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='orders.preparationarea'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='requires_preparation',
            field=models.BooleanField(default=True, help_text='Whether this item requires preparation (set False for packaged goods)'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='preparation_routing_enabled',
            field=models.BooleanField(default=False, help_text='Route order items to separate preparation areas (bar, kitchen, etc.)'),
        ),
    ]
