# Generated by Django 6.0.6 on 2026-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0011_menuitem_preparation_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='ai_enabled',
            field=models.BooleanField(default=False, help_text='Enable AI features for this merchant (assistant chat, insights)'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='ai_insights_enabled',
            field=models.BooleanField(default=False, help_text='Enable daily AI-generated business insights'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='ai_insights_time',
            field=models.TimeField(blank=True, help_text='Preferred local time for daily insight generation', null=True),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='timezone',
            field=models.CharField(default='Asia/Kathmandu', help_text="Merchant's local timezone for scheduling", max_length=50),
        ),
    ]
