# Generated by Django 6.0.6 on 2026-08-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0012_merchantprofile_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='VAT rate applied to POS orders (set to 0 to disable)', max_digits=5),
        ),
    ]
