# Generated by Django 6.0.6 on 2026-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0013_add_tax_rate_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='currency_code',
            field=models.CharField(default='NPR', help_text='ISO 4217 currency code (e.g. NPR, INR, USD, THB)', max_length=3),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='currency_symbol',
            field=models.CharField(default='Rs', help_text='Display currency symbol (e.g. Rs, ₹, $, ฿)', max_length=5),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='tax_components',
            field=models.JSONField(blank=True, default=list, help_text='List of tax components, e.g. [{"name":"VAT","rate":13}] or [{"name":"CGST","rate":9},{"name":"SGST","rate":9}]. Falls back to tax_rate_percent when empty.'),
        ),
        migrations.AlterField(
            model_name='merchantprofile',
            name='tax_rate_percent',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Legacy VAT rate. Kept for backward compat; prefer tax_components.', max_digits=5),
        ),
    ]
