# Generated by Django 6.0.6 on 2026-08-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0015_seed_tax_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='tax_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle: enable/disable tax calculations system-wide'),
        ),
    ]
