# Generated by Django 6.0.6 on 2026-08-27 07:23

from django.db import migrations, models


def backfill_pdf_menu_tokens(apps, schema_editor):
    import secrets
    MerchantProfile = apps.get_model("merchants", "MerchantProfile")
    for m in MerchantProfile.objects.filter(pdf_menu_token=""):
        token = f"MENU-{secrets.token_urlsafe(8)}".upper()
        while MerchantProfile.objects.filter(pdf_menu_token=token).exclude(pk=m.pk).exists():
            token = f"MENU-{secrets.token_urlsafe(8)}".upper()
        m.pdf_menu_token = token
        m.save(update_fields=["pdf_menu_token"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0016_merchantprofile_tax_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='pdf_menu_token',
            field=models.CharField(blank=True, editable=False, help_text='Public token for accessing the PDF menu via QR', max_length=64),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='pdf_menu_url',
            field=models.URLField(blank=True, default='', help_text='URL of the uploaded PDF menu file'),
        ),
        migrations.RunPython(backfill_pdf_menu_tokens, noop),
    ]
