# Generated by Django 6.0.6 on 2026-08-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0017_add_pdf_menu_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='pdf_menu_page_count',
            field=models.IntegerField(default=0, help_text='Number of pages rendered as images from the uploaded PDF menu'),
        ),
    ]
