# Generated by Django 6.0.8 on 2026-09-21 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0018_merchantprofile_pdf_menu_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["dairy", "nuts", "shellfish"]'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='dietary_tags',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["vegetarian", "vegan", "spicy", "gluten-free", "bestseller"]'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='short_description',
            field=models.CharField(blank=True, help_text='One-line subtitle shown under the product tile name.', max_length=200),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', help_text='Lifecycle status; archived items are hidden everywhere.', max_length=20),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'menu_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='merchants.menucategory'),
        ),
        migrations.CreateModel(
            name='MenuOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('variant', 'Variant'), ('modifier', 'Modifier')], default='modifier', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('min_select', models.PositiveIntegerField(default=0)),
                ('max_select', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='merchants.menuitem')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'menu_option_groups',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Absolute price for variant options. Falls back to the item price when null.', max_digits=10, null=True)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, help_text='Price add-on for modifier options (e.g. +50 for extra cheese).', max_digits=10)),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_options', to='merchants.merchantprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='merchants.menuoptiongroup')),
            ],
            options={
                'db_table': 'menu_options',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('merchant', 'name'), name='unique_category_name_per_merchant'),
        ),
        migrations.AddConstraint(
            model_name='menuoptiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('min_select__gte', 0), ('max_select__gte', 1)), name='menu_option_group_selection_bounds'),
        ),
    ]
