# Generated by Django 6.0.8 on 2026-09-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0020_backfill_menu_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discount_source',
            field=models.CharField(choices=[('manual', 'Set by merchant'), ('special', "Synced from Today's Special")], default='manual', help_text="Whether the discount was set directly or synced from a Today's Special.", max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No discount'), ('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='none', help_text='Item-level discount applied to the base price (variants keep their own price).', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (0-100) or fixed amount depending on discount_type.', max_digits=10, null=True),
        ),
    ]
