# Generated by Django 6.0.8 on 2026-09-25 16:06

from django.db import migrations, models


def normalise_required_groups(apps, schema_editor):
    """
    Make existing data satisfy the new selection-bounds constraints.

    Two legacy shapes are possible in a pre-constraint database:

    1. `required=True` with `min_select=0`. "Required" can only mean "at least
       one", so raise the floor to 1. A group nobody could satisfy would have
       been unorderable, so this reflects the merchant's real intent.
    2. `min_select > max_select`. No valid selection could ever exist; clamp
       the floor down to the ceiling so the group stays orderable.
    """
    Group = apps.get_model("merchants", "MenuOptionGroup")
    db = schema_editor.connection.alias
    Group.objects.using(db).filter(required=True, min_select=0).update(min_select=1)
    Group.objects.using(db).filter(min_select__gt=models.F("max_select")).update(
        min_select=models.F("max_select")
    )


def noop_reverse(apps, schema_editor):
    """
    Reverse is intentionally lossy-free: the constraints are dropped by the
    AddConstraint operations, and we do not guess which groups used to be
    "required but optional" before the backfill.
    """


class Migration(migrations.Migration):

    dependencies = [
        # Upstream added `payment_qr_url` on its own 0022. Depend on it rather
        # than forking the graph: this migration used to re-add the same field
        # with an identical definition, which made two leaf nodes and forced a
        # merge migration. The field is now added exactly once, by the earlier
        # migration, so databases that already applied it are unaffected.
        ('merchants', '0022_merchantprofile_payment_qr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantprofile',
            name='accepted_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of payment method keys this merchant accepts, e.g. ["cash", "card", "bank_qr", "other"]. Empty means "not configured".'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='payment_method_labels',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-method display overrides, e.g. {"bank_qr": "Fonepay QR", "mobile_wallet": "eSewa"}.'),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='payment_methods_configured',
            field=models.BooleanField(default=False, help_text="True once the merchant has saved an explicit accepted-methods list"),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='payment_qr_account_name',
            field=models.CharField(blank=True, default='', help_text='Account or display name printed under the QR', max_length=120),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='payment_qr_enabled',
            field=models.BooleanField(default=False, help_text="Show this merchant's payment QR when a QR payment is selected"),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='payment_qr_instructions',
            field=models.CharField(blank=True, default='', help_text='Short customer-facing hint, e.g. "Scan the QR and show confirmation to staff."', max_length=255),
        ),
        migrations.AddField(
            model_name='merchantprofile',
            name='payment_qr_name',
            field=models.CharField(blank=True, default='', help_text='Display name for the QR, e.g. "Fonepay QR" or "eSewa"', max_length=80),
        ),
        # `payment_qr_url` is intentionally absent: the dependency migration
        # 0022_merchantprofile_payment_qr_url already adds it with an identical
        # definition, and adding it twice is what produced the forked graph.
        # Must precede the constraints below: legacy rows may not satisfy them.
        migrations.RunPython(normalise_required_groups, noop_reverse),
        migrations.AddConstraint(
            model_name='menuoption',
            constraint=models.CheckConstraint(condition=models.Q(('price_delta__gte', 0)), name='menu_option_price_delta_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuoption',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='menu_option_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='menuoptiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('min_select', 0), ('required', True), _negated=True), name='menu_option_group_required_has_min'),
        ),
        migrations.AddConstraint(
            model_name='menuoptiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'variant'), ('max_select__gt', 1), _negated=True), name='menu_option_group_variant_single_select'),
        ),
        migrations.AddConstraint(
            model_name='menuoptiongroup',
            constraint=models.CheckConstraint(condition=models.Q(('min_select__lte', models.F('max_select'))), name='menu_option_group_min_le_max'),
        ),
    ]
