# Generated by Django 6.0.8 on 2026-09-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0021_menuitem_discount_source_menuitem_discount_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="payment_qr_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Merchant's own payment QR image, shown at POS for QR payments",
            ),
        ),
    ]
