# Generated by Django 6.0.8 on 2026-09-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0022_merchant_payment_and_menu_option_hardening"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="calories",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Energy per serving in kcal; blank when unknown.",
                null=True,
            ),
        ),
    ]
