# Generated by Django 6.0.8 on 2026-09-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0023_menuitem_calories"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="tax_class",
            field=models.CharField(
                choices=[
                    ("standard", "Standard (taxed)"),
                    ("exempt", "Tax exempt"),
                    ("zero_rated", "Zero-rated"),
                ],
                default="standard",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="service_charge_dine_in_only",
            field=models.BooleanField(
                default=True,
                help_text="Apply the service charge to dine-in orders only.",
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="service_charge_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Service charge added to orders, as a percent of the discounted goods value (0 = off).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="tax_policy",
            field=models.CharField(
                choices=[
                    ("legacy", "Tax on full price, before discounts (legacy)"),
                    (
                        "exclusive",
                        "Tax added at checkout; discounts reduce the taxable value",
                    ),
                    (
                        "inclusive",
                        "Prices include tax; discounts reduce the taxable value",
                    ),
                ],
                default="legacy",
                max_length=20,
            ),
        ),
    ]
