# Generated by Django 6.0.8 on 2026-09-29 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0024_pricing_v1"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="area",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Neighbourhood / area within the city, for 'choose your area' filtering.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="city",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=80
            ),
        ),
        migrations.CreateModel(
            name="MerchantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("icon", models.CharField(blank=True, default="", max_length=8)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="merchants.merchantcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "merchant categories",
                "db_table": "merchant_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="primary_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Controlled category used for discovery (replaces free-text business_type).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merchants",
                to="merchants.merchantcategory",
            ),
        ),
    ]
