# Generated by Django 6.0.8 on 2026-10-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0026_seed_merchant_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchanttable",
            name="seats",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.CreateModel(
            name="TableArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reserved for future multi-branch support. Null = the merchant's single location.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_areas",
                        to="merchants.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "merchant_table_areas",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="merchanttable",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tables",
                to="merchants.tablearea",
            ),
        ),
        migrations.AddConstraint(
            model_name="tablearea",
            constraint=models.UniqueConstraint(
                fields=("merchant", "name"), name="unique_table_area_name_per_merchant"
            ),
        ),
    ]
