# Generated by Django 6.0.8 on 2026-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0028_default_table_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantprofile",
            name="free_item_pin_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hashed PIN staff must enter to give a free item (empty = no PIN)",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="free_items_enabled",
            field=models.BooleanField(
                default=False, help_text="Allow staff to give free items at the POS"
            ),
        ),
    ]
