# Generated by Django 6.0.6 on 2026-07-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_preparation_ready_at_and_more'),
        ('pos', '0005_add_debit_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPreparationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='orders.preparationarea')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_area_assignments', to='pos.shiftworker')),
            ],
            options={
                'db_table': 'staff_preparation_areas',
                'constraints': [models.UniqueConstraint(fields=('worker', 'preparation_area'), name='unique_worker_preparation_area')],
            },
        ),
    ]
