# Generated by Django 6.0.6 on 2026-08-02 17:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0012_merchantprofile_ai_enabled_and_more'),
        ('orders', '0017_orderitem_preparation_ready_by'),
        ('pos', '0006_staffpreparationarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posauditlog',
            name='action',
            field=models.CharField(choices=[('device_register', 'Device Register'), ('device_deactivate', 'Device Deactivate'), ('worker_login', 'Worker Login'), ('worker_logout', 'Worker Logout'), ('worker_create', 'Worker Create'), ('worker_update', 'Worker Update'), ('shift_open', 'Shift Open'), ('shift_close', 'Shift Close'), ('staff_shift_open', 'Staff Shift Open'), ('staff_shift_close', 'Staff Shift Close'), ('order_create', 'Order Create'), ('order_update', 'Order Update'), ('order_cancel', 'Order Cancel'), ('discount_apply', 'Discount Apply'), ('payment', 'Payment'), ('refund', 'Refund'), ('credit_sale', 'Credit Sale'), ('credit_repay', 'Credit Repay'), ('debit_topup', 'Debit Top-up'), ('debit_purchase', 'Debit Purchase'), ('debit_adjustment', 'Debit Adjustment'), ('sync_attempt', 'Sync Attempt'), ('sync_conflict', 'Sync Conflict'), ('sync_resolve', 'Sync Resolve'), ('report_generate', 'Report Generate'), ('merchant_login', 'Merchant Login')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_from_device_id', models.CharField(blank=True, default='', help_text='POS device that started this shift', max_length=100)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_staff_shifts', to='pos.shiftworker')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_shifts', to='merchants.merchantprofile')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_shifts', to='pos.shiftworker')),
            ],
            options={
                'db_table': 'pos_staff_shifts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffShiftArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_shift_assignments', to='orders.preparationarea')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_assignments', to='pos.staffshift')),
            ],
            options={
                'db_table': 'pos_staff_shift_areas',
            },
        ),
        migrations.AddConstraint(
            model_name='staffshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('worker', 'status'), name='unique_active_staff_shift_per_worker'),
        ),
        migrations.AddConstraint(
            model_name='staffshiftarea',
            constraint=models.UniqueConstraint(fields=('shift', 'preparation_area'), name='unique_staff_shift_area'),
        ),
    ]
