# Generated by Django 6.0.6 on 2026-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0012_merchantprofile_ai_enabled_and_more'),
        ('orders', '0019_order_orders_merchant_created_idx_and_more'),
        ('pos', '0007_alter_posauditlog_action_staffshift_staffshiftarea_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['shift', 'status'], name='pospay_shift_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pospayment',
            index=models.Index(fields=['order', 'status'], name='pospay_order_status_idx'),
        ),
    ]
