# Generated by Django 6.0.6 on 2026-08-26 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0016_merchantprofile_tax_enabled'),
        ('pos', '0008_pospayment_pospay_shift_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('tax', 'Tax Report'), ('fiscal', 'Fiscal Report'), ('payment', 'Payment Report'), ('cash', 'Cash Report'), ('online_payment', 'Online Payment Report'), ('product', 'Product Sales Report'), ('category', 'Category Sales Report'), ('refund', 'Refund Report'), ('discount', 'Discount Report'), ('order', 'Order Report'), ('analytics', 'Analytics Report')], max_length=30)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Spreadsheet')], max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Snapshot of the filters used when generating this report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_history', to='merchants.merchantprofile')),
            ],
            options={
                'db_table': 'pos_report_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
