# Generated by Django 6.0.8 on 2026-09-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0009_reporthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pospayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("bank_qr", "QR Payment"),
                    ("mobile_wallet", "Digital Payment"),
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("split", "Split"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
