# Generated by Django 6.0.8 on 2026-10-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0027_table_areas_and_roles"),
        ("pos", "0010_pospayment_method_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("device_register", "Device Register"),
                    ("device_deactivate", "Device Deactivate"),
                    ("worker_login", "Worker Login"),
                    ("worker_logout", "Worker Logout"),
                    ("worker_create", "Worker Create"),
                    ("worker_update", "Worker Update"),
                    ("shift_open", "Shift Open"),
                    ("shift_close", "Shift Close"),
                    ("staff_shift_open", "Staff Shift Open"),
                    ("staff_shift_close", "Staff Shift Close"),
                    ("order_create", "Order Create"),
                    ("order_update", "Order Update"),
                    ("order_cancel", "Order Cancel"),
                    ("discount_apply", "Discount Apply"),
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("credit_sale", "Credit Sale"),
                    ("credit_repay", "Credit Repay"),
                    ("debit_topup", "Debit Top-up"),
                    ("debit_purchase", "Debit Purchase"),
                    ("debit_adjustment", "Debit Adjustment"),
                    ("sync_attempt", "Sync Attempt"),
                    ("sync_conflict", "Sync Conflict"),
                    ("sync_resolve", "Sync Resolve"),
                    ("report_generate", "Report Generate"),
                    ("merchant_login", "Merchant Login"),
                    ("role_create", "Role Create"),
                    ("role_update", "Role Update"),
                    ("role_deactivate", "Role Deactivate"),
                    ("worker_role_change", "Worker Role Change"),
                    ("worker_areas_change", "Worker Areas Change"),
                    ("table_area_create", "Table Area Create"),
                    ("table_area_update", "Table Area Update"),
                    ("table_move", "Table Move"),
                    ("staff_mode", "Staff Mode"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="StaffAreaAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="merchants.tablearea",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_assignments",
                        to="pos.shiftworker",
                    ),
                ),
            ],
            options={
                "db_table": "pos_staff_area_assignments",
            },
        ),
        migrations.AddField(
            model_name="shiftworker",
            name="table_areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="workers",
                through="pos.StaffAreaAssignment",
                to="merchants.tablearea",
            ),
        ),
        migrations.CreateModel(
            name="StaffRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "system_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="admin/manager/cashier/server/kitchen/inventory for default roles; blank for custom roles.",
                        max_length=20,
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Protected full-access role. Always passes every permission inside its own merchant.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_roles",
                        to="merchants.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "pos_staff_roles",
                "ordering": ["-is_admin", "-is_system", "name"],
            },
        ),
        migrations.AddField(
            model_name="shiftworker",
            name="staff_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workers",
                to="pos.staffrole",
            ),
        ),
        migrations.CreateModel(
            name="StaffRolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission_code", models.CharField(max_length=40)),
                ("allowed", models.BooleanField(default=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="pos.staffrole",
                    ),
                ),
            ],
            options={
                "db_table": "pos_staff_role_permissions",
            },
        ),
        migrations.AddConstraint(
            model_name="staffareaassignment",
            constraint=models.UniqueConstraint(
                fields=("worker", "table_area"), name="unique_worker_table_area"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffrole",
            constraint=models.UniqueConstraint(
                fields=("merchant", "name"), name="unique_staff_role_name_per_merchant"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffrolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission_code"), name="unique_role_permission"
            ),
        ),
    ]
