# Generated by Django 6.0.8 on 2026-10-02 05:37

from django.db import migrations, models


def populate_staff_codes(apps, schema_editor):
    ShiftWorker = apps.get_model("pos", "ShiftWorker")
    merchant_ids = ShiftWorker.objects.values_list("merchant_id", flat=True).distinct()
    for m_id in merchant_ids:
        workers = list(ShiftWorker.objects.filter(merchant_id=m_id).order_by("created_at"))
        code = 1001
        for w in workers:
            if not w.staff_code:
                w.staff_code = str(code)
                w.save(update_fields=["staff_code"])
                code += 1


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0028_default_table_area"),
        ("pos", "0012_seed_roles_for_existing_workers"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftworker",
            name="email",
            field=models.EmailField(
                blank=True, default="", help_text="Staff email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="shiftworker",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shiftworker",
            name="phone",
            field=models.CharField(
                blank=True, default="", help_text="Contact phone number", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="shiftworker",
            name="staff_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Unique staff code for POS login, e.g. 1001",
                max_length=30,
            ),
        ),
        migrations.RunPython(populate_staff_codes, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="shiftworker",
            constraint=models.UniqueConstraint(
                condition=models.Q(("staff_code__gt", "")),
                fields=("merchant", "staff_code"),
                name="unique_worker_staff_code_per_merchant",
            ),
        ),
    ]

