# Generated by Django 6.0.8 on 2026-10-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_posauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftworker',
            name='pin_plain',
            field=models.CharField(blank=True, default='', help_text='Plain PIN for merchant display', max_length=8),
        ),
    ]
