# Generated by Django 6.0.8 on 2026-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0016_shiftworker_pin_plain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("device_register", "Device Register"),
                    ("device_deactivate", "Device Deactivate"),
                    ("worker_login", "Worker Login"),
                    ("worker_logout", "Worker Logout"),
                    ("worker_create", "Worker Create"),
                    ("worker_update", "Worker Update"),
                    ("shift_open", "Shift Open"),
                    ("shift_close", "Shift Close"),
                    ("staff_shift_open", "Staff Shift Open"),
                    ("staff_shift_close", "Staff Shift Close"),
                    ("order_create", "Order Create"),
                    ("order_update", "Order Update"),
                    ("order_cancel", "Order Cancel"),
                    ("discount_apply", "Discount Apply"),
                    ("payment", "Payment"),
                    ("refund", "Refund"),
                    ("credit_sale", "Credit Sale"),
                    ("credit_repay", "Credit Repay"),
                    ("debit_topup", "Debit Top-up"),
                    ("debit_purchase", "Debit Purchase"),
                    ("debit_adjustment", "Debit Adjustment"),
                    ("sync_attempt", "Sync Attempt"),
                    ("sync_conflict", "Sync Conflict"),
                    ("sync_resolve", "Sync Resolve"),
                    ("report_generate", "Report Generate"),
                    ("merchant_login", "Merchant Login"),
                    ("role_create", "Role Create"),
                    ("role_update", "Role Update"),
                    ("role_deactivate", "Role Deactivate"),
                    ("worker_role_change", "Worker Role Change"),
                    ("worker_areas_change", "Worker Areas Change"),
                    ("table_area_create", "Table Area Create"),
                    ("table_area_update", "Table Area Update"),
                    ("table_move", "Table Move"),
                    ("staff_mode", "Staff Mode"),
                    ("punch_card_redeem", "Punch Card Redeem"),
                    ("reward_redeem", "Reward Redeem"),
                    ("free_item", "Free Item"),
                    ("order_item_update", "Order Item Update"),
                    ("discount_remove", "Discount Remove"),
                    ("settings_update", "Settings Update"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
