USE_CASE_MERCHANT_ASSISTANT = "merchant_assistant"
USE_CASE_DAILY_INSIGHTS = "daily_insights"

REQUEST_STATUS_QUEUED = "queued"
REQUEST_STATUS_RUNNING = "running"
REQUEST_STATUS_COMPLETED = "completed"
REQUEST_STATUS_FAILED = "failed"

REQUEST_STATUS_CHOICES = [
    (REQUEST_STATUS_QUEUED, "Queued"),
    (REQUEST_STATUS_RUNNING, "Running"),
    (REQUEST_STATUS_COMPLETED, "Completed"),
    (REQUEST_STATUS_FAILED, "Failed"),
]

ARTIFACT_TYPE_DAILY_INSIGHT = "daily_insight"
ARTIFACT_TYPE_CHAT_RESPONSE = "chat_response"

CAPABILITY_TEXT_GENERATION = "text_generation"
CAPABILITY_STRUCTURED_GENERATION = "structured_generation"
CAPABILITY_CHAT = "chat"
CAPABILITY_TOOL_CALLING = "tool_calling"

MAX_CHAT_MESSAGE_LENGTH = 10000
MAX_TOOL_OUTPUT_LENGTH = 50000
