# Generated by Django 6.0.6 on 2026-07-29 12:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0012_merchantprofile_ai_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='merchants.merchantprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_case', models.CharField(db_index=True, max_length=50)),
                ('model_alias', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=50)),
                ('provider_model', models.CharField(blank=True, max_length=100)),
                ('prompt_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('capability', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('used_fallback', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('sanitized_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='merchants.merchantprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('tool_results', models.JSONField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_core.aiconversation')),
                ('ai_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.airequest')),
            ],
            options={
                'db_table': 'ai_conversation_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(db_index=True, max_length=50)),
                ('schema_version', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('structured_content', models.JSONField(default=dict)),
                ('effective_date', models.DateField(blank=True, db_index=True, null=True)),
                ('prompt_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('context_schema_version', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_artifacts', to='merchants.merchantprofile')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='ai_core.airequest')),
            ],
            options={
                'db_table': 'ai_artifacts',
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['merchant', 'updated_at'], name='ai_conversa_merchan_227b07_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['merchant', 'created_at'], name='ai_requests_merchan_1c9fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['merchant', 'use_case', 'created_at'], name='ai_requests_merchan_078abe_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['status', 'created_at'], name='ai_requests_status_bb25fd_idx'),
        ),
        migrations.AddIndex(
            model_name='aiartifact',
            index=models.Index(fields=['merchant', 'artifact_type', 'effective_date'], name='ai_artifact_merchan_0f15a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='aiartifact',
            constraint=models.UniqueConstraint(fields=('merchant', 'artifact_type', 'effective_date', 'schema_version', 'prompt_version'), name='unique_artifact_per_merchant'),
        ),
    ]
