# Generated by Django 6.0.6 on 2026-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customerprofile_transfer_code'),
        ('loyalty', '0020_fix_restart_interval_default'),
        ('merchants', '0012_merchantprofile_ai_enabled_and_more'),
        ('orders', '0018_orderitem_preparation_staff_shift_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['merchant', 'customer', '-created_at'], name='pt_merchant_customer_idx'),
        ),
    ]
