# Generated by Django 6.0.6 on 2026-09-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0022_todayspecial_discount_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed'), ('REDEMPTION_REFUND', 'Redemption Refund'), ('MISSION_BONUS', 'Mission Bonus'), ('PUNCH_CARD_REWARD', 'Punch Card Reward'), ('EXPIRED', 'Expired'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('TRANSFER_SENT', 'Transfer Sent'), ('TRANSFER_RECEIVED', 'Transfer Received')], max_length=50),
        ),
    ]
