# Generated by Django 6.0.8 on 2026-09-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0023_alter_pointtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayspecial',
            name='cta_label',
            field=models.CharField(blank=True, default='Order now', help_text='Call-to-action text on the banner button.', max_length=60),
        ),
        migrations.AddField(
            model_name='todayspecial',
            name='ends_at',
            field=models.DateTimeField(blank=True, help_text='Optional: special only shows until this time (local to merchant timezone).', null=True),
        ),
        migrations.AddField(
            model_name='todayspecial',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Optional: special only shows from this time (local to merchant timezone).', null=True),
        ),
    ]
