# Generated by Django 6.0.8 on 2026-09-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_google_sub_user_phone_verified_otpcode'),
        ('loyalty', '0025_backfill_special_menu_item_discounts'),
        ('merchants', '0021_menuitem_discount_source_menuitem_discount_type_and_more'),
        ('orders', '0024_orderitem_special_instructions_orderitemoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchCardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STARTED', 'Started'), ('PUNCHED', 'Punched'), ('COMPLETED', 'Completed'), ('REDEEMED', 'Claimed')], max_length=20)),
                ('stamp_number', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='loyalty.customerpunchcard')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_card_events', to='accounts.customerprofile')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_card_events', to='merchants.merchantprofile')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_card_events', to='orders.order')),
                ('punch_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='loyalty.merchantpunchcard')),
            ],
            options={
                'db_table': 'loyalty_punch_card_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'event_type'], name='loyalty_pun_merchan_f4c8bd_idx'), models.Index(fields=['merchant', '-created_at'], name='loyalty_pun_merchan_5b64af_idx'), models.Index(fields=['customer', '-created_at'], name='loyalty_pun_custome_5a1fe4_idx'), models.Index(fields=['card', 'created_at'], name='loyalty_pun_card_id_3c92ea_idx')],
            },
        ),
    ]
