# Generated by Django 6.0.8 on 2026-10-08 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0004_inventory_simplify_import_approval"),
        ("merchants", "0030_addons_optional_free_items_existing"),
        ("pos", "0018_grant_free_items_and_accounts_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "opening_bank",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "opening_date",
                    models.DateField(
                        blank=True,
                        help_text="Balances count money from this day on. Empty = from the first record.",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_settings",
                        to="merchants.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "finance_settings",
            },
        ),
        migrations.CreateModel(
            name="StaffSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_name",
                    models.CharField(
                        help_text="Name at the time, kept if the employee is removed.",
                        max_length=120,
                    ),
                ),
                (
                    "period",
                    models.DateField(
                        help_text="First day of the month this salary is for."
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_salaries",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salaries",
                        to="pos.shiftworker",
                    ),
                ),
            ],
            options={
                "db_table": "finance_staff_salaries",
                "ordering": ["-period", "worker_name"],
            },
        ),
        migrations.CreateModel(
            name="MoneyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("expense", "Expense"),
                            ("supplier_payment", "Supplier payment"),
                            ("salary_payment", "Salary payment"),
                            ("other_income", "Other income"),
                            ("bank_deposit", "Cash put in the bank"),
                            ("bank_withdrawal", "Cash taken from the bank"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Always positive.", max_digits=14
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank transfer"),
                            ("online", "Online / wallet"),
                            ("cheque", "Cheque"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("category", models.CharField(blank=True, default="", max_length=24)),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sent by the form so a double tap or retry never records the money twice.",
                        max_length=64,
                    ),
                ),
                ("is_void", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "voided_by_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_entries",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "receiving",
                    models.ForeignKey(
                        blank=True,
                        help_text="The delivery this supplier payment is for, when the merchant picked one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="money_entries",
                        to="inventory.inventoryreceiving",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="money_entries",
                        to="inventory.supplier",
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.staffsalary",
                    ),
                ),
            ],
            options={
                "db_table": "finance_money_entries",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="staffsalary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("worker__isnull", False)),
                fields=("merchant", "worker", "period"),
                name="uniq_staff_salary_per_month",
            ),
        ),
        migrations.AddIndex(
            model_name="moneyentry",
            index=models.Index(
                fields=["merchant", "date"], name="fin_entry_merchant_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moneyentry",
            index=models.Index(
                fields=["merchant", "kind", "date"], name="fin_entry_kind_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="moneyentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="fin_entry_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="moneyentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_key", ""), _negated=True),
                fields=("merchant", "client_key"),
                name="uniq_fin_entry_client_key",
            ),
        ),
    ]
