# Generated by Django 6.0.8 on 2026-09-23 03:14

from django.db import migrations, models


def dedupe_system_units(apps, schema_editor):
    """Collapse duplicate system (merchant IS NULL) units into the oldest row.

    Pre-migration databases may already hold ''g'' / ''mg'' duplicates created
    by racing requests (NULL merchant made the (merchant, code) constraint a
    no-op). Remove extras before the partial unique index is created.
    """
    UnitOfMeasure = apps.get_model("inventory", "UnitOfMeasure")
    for code in UnitOfMeasure.objects.filter(merchant__isnull=True).values_list(
        "code", flat=True
    ).distinct():
        rows = list(
            UnitOfMeasure.objects.filter(merchant__isnull=True, code=code).order_by("id")
        )
        if len(rows) <= 1:
            continue
        keep = rows[0]
        for drop in rows[1:]:
            inventory_item_model = apps.get_model("inventory", "InventoryItem")
            inventory_item_model.objects.filter(base_unit=drop).update(base_unit=keep)
            inventory_item_model.objects.filter(preferred_display_unit=drop).update(
                preferred_display_unit=keep
            )
            drop.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('merchants', '0021_menuitem_discount_source_menuitem_discount_type_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_system_units, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(condition=models.Q(('merchant__isnull', True)), fields=('code',), name='uniq_inventory_system_unit_code'),
        ),
    ]
