# Generated by Django 6.0.8 on 2026-09-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_unitofmeasure_uniq_inventory_system_unit_code"),
        ("merchants", "0021_menuitem_discount_source_menuitem_discount_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("OPENING_BALANCE", "Opening Balance"),
                    ("RECEIVE", "Receiving"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("EXPLICIT_WASTE", "Explicit Waste"),
                    ("MANUAL_ADJUSTMENT", "Manual Adjustment"),
                    ("COUNT_RECONCILIATION", "Count Reconciliation"),
                    ("RETURN_TO_SUPPLIER", "Return to Supplier"),
                    ("REVERSAL", "Reversal"),
                    ("SALE", "Sale"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ITEM_CREATE", "Item Create"),
                    ("RECEIVING", "Receiving"),
                    ("PO_RECEIVE", "Purchase Order Receiving"),
                    ("WASTE_RECORD", "Waste Record"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("TRANSFER", "Transfer"),
                    ("STOCK_COUNT", "Stock Count"),
                    ("SUPPLIER_RETURN", "Supplier Return"),
                    ("REVERSAL", "Reversal"),
                    ("ORDER", "Order"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="MenuItemStockLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_per_unit",
                    models.DecimalField(
                        decimal_places=6,
                        default=1,
                        help_text="Base units of the inventory item consumed per menu item sold.",
                        max_digits=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_links",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_links",
                        to="merchants.menuitem",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_stock_links",
                        to="merchants.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_menu_item_links",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("menu_item", "inventory_item"),
                        name="uniq_inventory_menu_item_link",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity_per_unit__gt", 0)),
                        name="ck_inventory_menu_link_qty_pos",
                    ),
                ],
            },
        ),
    ]
