# Generated by Django 6.0.8 on 2026-09-30 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_menu_item_stock_link"),
        ("merchants", "0026_seed_merchant_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("PDF", "PDF")], max_length=10
                    ),
                ),
                ("file_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "import_mode",
                    models.CharField(
                        choices=[
                            ("NEW_ITEMS", "New stock items"),
                            ("UPDATE_ITEMS", "Update item details"),
                            ("STOCK_COUNT", "Physical stock count"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALIDATING", "Validating"),
                            ("READY", "Ready to review"),
                            ("IMPORTING", "Importing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="VALIDATING",
                        max_length=20,
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="csv | pdf_text | pdf_ai — how rows were read from the file.",
                        max_length=20,
                    ),
                ),
                ("rows", models.JSONField(blank=True, default=list)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("rows_total", models.PositiveIntegerField(default=0)),
                ("rows_imported", models.PositiveIntegerField(default=0)),
                ("rows_skipped", models.PositiveIntegerField(default=0)),
                ("rows_failed", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "inventory_import_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inventoryadjustment",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryadjustment",
            name="idempotency_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="inventoryadjustment",
            name="performed_by_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Staff member (POS worker) who requested it, when not the account owner.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="inventoryadjustment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="actor_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Staff member (POS worker in staff mode) who recorded it, if not the owner.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="inventoryreceiving",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Client key so a retried 'Add to Stock' never records the delivery twice.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="inventorysettings",
            name="po_seq",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventorysettings",
            name="receipt_seq",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inventorywasterecord",
            name="performed_by_label",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="inventoryauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("item_created", "Item Created"),
                    ("item_updated", "Item Updated"),
                    ("opening_stock", "Opening Stock"),
                    ("receiving", "Receiving"),
                    ("po_created", "Purchase Order Created"),
                    ("po_received", "Purchase Order Received"),
                    ("count_started", "Count Started"),
                    ("count_submitted", "Count Submitted"),
                    ("count_approved", "Count Approved"),
                    ("count_cancelled", "Count Cancelled"),
                    ("waste", "Waste"),
                    ("adjustment", "Adjustment"),
                    ("transfer", "Transfer"),
                    ("transfer_complete", "Transfer Complete"),
                    ("supplier_edit", "Supplier Edit"),
                    ("settings_updated", "Settings Updated"),
                    ("reversal", "Reversal"),
                    ("item_deleted", "Item Deleted"),
                    ("item_archived", "Item Archived"),
                    ("adjustment_requested", "Adjustment Requested"),
                    ("adjustment_approved", "Adjustment Approved"),
                    ("adjustment_rejected", "Adjustment Rejected"),
                    ("import", "Import"),
                    ("export", "Export"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryreceiving",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("merchant", "idempotency_key"),
                name="uniq_inventory_receiving_idem_key",
            ),
        ),
        migrations.AddField(
            model_name="inventoryimportsession",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inventory.inventoryimportsession",
            ),
        ),
        migrations.AddField(
            model_name="inventoryimportsession",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Fallback location for rows that do not name one.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="inventory.inventorylocation",
            ),
        ),
        migrations.AddField(
            model_name="inventoryimportsession",
            name="merchant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_import_sessions",
                to="merchants.merchantprofile",
            ),
        ),
        migrations.AddField(
            model_name="inventoryimportsession",
            name="stock_count",
            field=models.ForeignKey(
                blank=True,
                help_text="Draft count created by a STOCK_COUNT import (stock changes only when it is approved).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_sessions",
                to="inventory.stockcount",
            ),
        ),
        migrations.AddField(
            model_name="inventoryimportsession",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_import_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryimportsession",
            index=models.Index(
                fields=["merchant", "file_hash"], name="inv_import_merchant_hash_idx"
            ),
        ),
    ]
