# Generated by Django 6.0.8 on 2026-09-29 05:25

import django.db.models.deletion
import offers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_google_sub_user_phone_verified_otpcode"),
        ("merchants", "0026_seed_merchant_categories"),
        ("orders", "0028_offers_line_snapshot"),
        ("pos", "0010_pospayment_method_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("terms", models.TextField(blank=True, default="")),
                ("image_url", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("link_only", "Private link / QR poster"),
                        ],
                        default="public",
                        max_length=12,
                    ),
                ),
                (
                    "channels",
                    models.CharField(
                        choices=[
                            ("all", "Online and in store"),
                            ("online", "Online orders only"),
                            ("in_store", "In store (POS) only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "link_token",
                    models.CharField(
                        default=offers.models._link_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, help_text="Null = as soon as published.", null=True
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, help_text="Null = no end date.", null=True
                    ),
                ),
                (
                    "claim_valid_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How long a claim stays usable after claiming (capped at ends_at).",
                        null=True,
                    ),
                ),
                ("max_claims", models.PositiveIntegerField(blank=True, null=True)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("per_customer_limit", models.PositiveIntegerField(default=1)),
                (
                    "min_order_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exclude_discounted_items",
                    models.BooleanField(
                        default=True,
                        help_text="Items already on a Today's Special neither qualify nor get discounted.",
                    ),
                ),
                (
                    "restore_on_cancel",
                    models.BooleanField(
                        default=True,
                        help_text="Give the use back if a redeemed order is later cancelled or refunded.",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("currency_code", models.CharField(default="NPR", max_length=3)),
                ("claims_count", models.PositiveIntegerField(default=0)),
                ("reserved_count", models.PositiveIntegerField(default=0)),
                ("redemptions_count", models.PositiveIntegerField(default=0)),
                ("is_hidden_by_admin", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_campaigns",
                        to="merchants.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("percent_off", "Percentage off"),
                            ("amount_off", "Amount off"),
                            ("free_item", "Free item"),
                            ("buy_x_get_y", "Buy X get Y"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("order", "Whole order"),
                            ("targets", "Selected products"),
                        ],
                        default="order",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percent (0–100) or amount for percent_off / amount_off.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("reward_quantity", models.PositiveIntegerField(default=1)),
                (
                    "reward_discount_percent",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "reward_selection",
                    models.CharField(
                        choices=[
                            ("customer_choice", "Customer chooses"),
                            ("cheapest", "Cheapest eligible"),
                        ],
                        default="customer_choice",
                        max_length=16,
                    ),
                ),
                ("max_applications", models.PositiveIntegerField(default=1)),
                (
                    "include_modifiers",
                    models.BooleanField(
                        default=False,
                        help_text="Add-ons on a reward item are free too (otherwise still charged).",
                    ),
                ),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit",
                        to="offers.promotioncampaign",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_benefits",
            },
        ),
        migrations.CreateModel(
            name="PromotionCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            (
                                "qualifying_items",
                                "Buy at least N of the qualifying products",
                            )
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="offers.promotioncampaign",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_conditions",
            },
        ),
        migrations.CreateModel(
            name="PromotionDailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("unique_viewers", models.PositiveIntegerField(default=0)),
                ("claims", models.PositiveIntegerField(default=0)),
                ("redemptions", models.PositiveIntegerField(default=0)),
                ("voids", models.PositiveIntegerField(default=0)),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sales_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("new_customers", models.PositiveIntegerField(default=0)),
                ("returning_customers", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="offers.promotioncampaign",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_daily_stats",
            },
        ),
        migrations.CreateModel(
            name="PromotionTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("benefit", "Benefit"), ("qualifying", "Qualifying")],
                        max_length=12,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="offers.promotioncampaign",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.menucategory",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.menuitem",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchants.menuoption",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_targets",
            },
        ),
        migrations.CreateModel(
            name="VoucherClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Normalised human code (no prefix/dashes).",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("qr_token", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved on an order"),
                            ("redeemed", "Used"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=10,
                    ),
                ),
                ("uses_allowed", models.PositiveIntegerField(default=1)),
                ("uses_count", models.PositiveIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("marketplace", "Marketplace"),
                            ("link", "Private link"),
                            ("merchant_issued", "Issued by merchant"),
                            ("automation", "Automation"),
                        ],
                        default="marketplace",
                        max_length=16,
                    ),
                ),
                ("campaign_version", models.PositiveIntegerField(default=1)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="offers.promotioncampaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_claims",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_claims",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "reserved_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserved_voucher_claims",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "voucher_claims",
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("online", "Online order"),
                            ("pos", "POS order"),
                            ("in_store", "In store"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("applied", "Applied"), ("voided", "Voided")],
                        default="applied",
                        max_length=8,
                    ),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "void_reason",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("currency_code", models.CharField(default="NPR", max_length=3)),
                (
                    "order_subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Priced by the engine; null for in-store confirmations without an order.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "order_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rules_snapshot", models.JSONField(default=dict)),
                (
                    "idempotency_key",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("is_new_customer", models.BooleanField(default=False)),
                ("returned_within_7d", models.BooleanField(blank=True, null=True)),
                ("returned_within_30d", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemptions",
                        to="offers.promotioncampaign",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redemptions",
                        to="offers.voucherclaim",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voucher_redemptions",
                        to="accounts.customerprofile",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_redemptions",
                        to="merchants.merchantprofile",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voucher_redemptions",
                        to="orders.order",
                    ),
                ),
                (
                    "redeemed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "redeemed_by_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="pos.shiftworker",
                    ),
                ),
            ],
            options={
                "db_table": "voucher_redemptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="promotioncampaign",
            index=models.Index(
                fields=["status", "visibility", "ends_at"], name="promo_discovery_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotioncampaign",
            index=models.Index(
                fields=["merchant", "status"], name="promo_merchant_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotioncampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("per_customer_limit__gte", 1)),
                name="promo_per_customer_limit_min_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotioncampaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_at__isnull", True),
                    ("starts_at__isnull", True),
                    ("ends_at__gt", models.F("starts_at")),
                    _connector="OR",
                ),
                name="promo_ends_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionbenefit",
            constraint=models.CheckConstraint(
                condition=models.Q(("reward_quantity__gte", 1)),
                name="promo_reward_qty_min_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionbenefit",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_applications__gte", 1)),
                name="promo_max_apps_min_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotionbenefit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reward_discount_percent__gt", 0),
                    ("reward_discount_percent__lte", 100),
                ),
                name="promo_reward_pct_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotioncondition",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="promo_condition_qty_min_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotiondailystats",
            constraint=models.UniqueConstraint(
                fields=("campaign", "date"), name="one_stats_row_per_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotiontarget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("category__isnull", True),
                        ("menu_item__isnull", False),
                        ("option__isnull", True),
                    ),
                    models.Q(
                        ("category__isnull", False),
                        ("menu_item__isnull", True),
                        ("option__isnull", True),
                    ),
                    models.Q(
                        ("category__isnull", True),
                        ("menu_item__isnull", True),
                        ("option__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="promo_target_exactly_one",
            ),
        ),
        migrations.AddIndex(
            model_name="voucherclaim",
            index=models.Index(
                fields=["customer", "status"], name="claim_customer_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherclaim",
            constraint=models.UniqueConstraint(
                fields=("campaign", "customer"),
                name="one_claim_per_customer_per_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherclaim",
            constraint=models.CheckConstraint(
                condition=models.Q(("uses_count__lte", models.F("uses_allowed"))),
                name="claim_uses_within_allowed",
            ),
        ),
        migrations.AddConstraint(
            model_name="voucherredemption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "applied"), ("order__isnull", False)),
                fields=("order",),
                name="one_applied_redemption_per_order",
            ),
        ),
    ]
