# Generated by Django 6.0.8 on 2026-09-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchants", "0026_seed_merchant_categories"),
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucherredemption",
            name="confirmed_via",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("pos", "POS"),
                    ("dashboard", "Merchant dashboard"),
                    ("pin", "Store PIN"),
                ],
                default="order",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="MerchantRedemptionPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin_hash", models.CharField(max_length=128)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_redemption_pin",
                        to="merchants.merchantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "merchant_redemption_pins",
            },
        ),
    ]
