/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PosRouteImport } from './routes/pos'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as StoresIdRouteImport } from './routes/stores_.$id'
import { Route as PosStaffReportRouteImport } from './routes/pos.staff-report'
import { Route as PosStaffRouteImport } from './routes/pos.staff'
import { Route as PosSettingsRouteImport } from './routes/pos.settings'
import { Route as PosScheduleRouteImport } from './routes/pos.schedule'
import { Route as PosReportsRouteImport } from './routes/pos.reports'
import { Route as PosPreparationRouteImport } from './routes/pos.preparation'
import { Route as PosOrdersRouteImport } from './routes/pos.orders'
import { Route as PosConflictsRouteImport } from './routes/pos.conflicts'
import { Route as PosCashMovementsRouteImport } from './routes/pos.cash-movements'
import { Route as PosAccountsRouteImport } from './routes/pos.accounts'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as MerchantTablesRouteImport } from './routes/merchant.tables'
import { Route as MerchantStoreRouteImport } from './routes/merchant.store'
import { Route as MerchantSpecialsRouteImport } from './routes/merchant.specials'
import { Route as MerchantPreparationRouteImport } from './routes/merchant.preparation'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantOnboardingRouteImport } from './routes/merchant.onboarding'
import { Route as MerchantMenuRouteImport } from './routes/merchant.menu'
import { Route as MerchantLoyaltyRouteImport } from './routes/merchant.loyalty'
import { Route as MerchantAnalyticsRouteImport } from './routes/merchant.analytics'
import { Route as MerchantAiRouteImport } from './routes/merchant.ai'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerOrderRouteImport } from './routes/customer.order'
import { Route as CustomerMerchantsRouteImport } from './routes/customer.merchants'
import { Route as CardsMerchantSlugRouteImport } from './routes/cards.$merchantSlug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthMerchantRouteImport } from './routes/auth.merchant'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as TableTokenOrderRouteImport } from './routes/table.$token.order'
import { Route as PosReportsZReportRouteImport } from './routes/pos.reports.z-report'
import { Route as PosPreparationAreaIdRouteImport } from './routes/pos.preparation.$areaId'
import { Route as LoyaltyQrTokenRouteImport } from './routes/loyalty.qr.$token'
import { Route as GuestMerchantSlugRouteImport } from './routes/guest.merchant.$slug'
import { Route as CustomerMerchantSlugRouteImport } from './routes/customer.merchant.$slug'
import { Route as AuthMerchantSignupRouteImport } from './routes/auth.merchant.signup'
import { Route as AuthMerchantLoginRouteImport } from './routes/auth.merchant.login'
import { Route as MSlugTableTokenRouteImport } from './routes/m.$slug.table.$token'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const StoresIdRoute = StoresIdRouteImport.update({
  id: '/stores_/$id',
  path: '/stores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PosStaffReportRoute = PosStaffReportRouteImport.update({
  id: '/staff-report',
  path: '/staff-report',
  getParentRoute: () => PosRoute,
} as any)
const PosStaffRoute = PosStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PosRoute,
} as any)
const PosSettingsRoute = PosSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PosRoute,
} as any)
const PosScheduleRoute = PosScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PosRoute,
} as any)
const PosReportsRoute = PosReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PosRoute,
} as any)
const PosPreparationRoute = PosPreparationRouteImport.update({
  id: '/preparation',
  path: '/preparation',
  getParentRoute: () => PosRoute,
} as any)
const PosOrdersRoute = PosOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PosRoute,
} as any)
const PosConflictsRoute = PosConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => PosRoute,
} as any)
const PosCashMovementsRoute = PosCashMovementsRouteImport.update({
  id: '/cash-movements',
  path: '/cash-movements',
  getParentRoute: () => PosRoute,
} as any)
const PosAccountsRoute = PosAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => PosRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantTablesRoute = MerchantTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantStoreRoute = MerchantStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantSpecialsRoute = MerchantSpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantPreparationRoute = MerchantPreparationRouteImport.update({
  id: '/preparation',
  path: '/preparation',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOnboardingRoute = MerchantOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantMenuRoute = MerchantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantLoyaltyRoute = MerchantLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantAnalyticsRoute = MerchantAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantAiRoute = MerchantAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => MerchantRoute,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrderRoute = CustomerOrderRouteImport.update({
  id: '/customer/order',
  path: '/customer/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMerchantsRoute = CustomerMerchantsRouteImport.update({
  id: '/customer/merchants',
  path: '/customer/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsMerchantSlugRoute = CardsMerchantSlugRouteImport.update({
  id: '/$merchantSlug',
  path: '/$merchantSlug',
  getParentRoute: () => CardsRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMerchantRoute = AuthMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const TableTokenOrderRoute = TableTokenOrderRouteImport.update({
  id: '/table/$token/order',
  path: '/table/$token/order',
  getParentRoute: () => rootRouteImport,
} as any)
const PosReportsZReportRoute = PosReportsZReportRouteImport.update({
  id: '/z-report',
  path: '/z-report',
  getParentRoute: () => PosReportsRoute,
} as any)
const PosPreparationAreaIdRoute = PosPreparationAreaIdRouteImport.update({
  id: '/$areaId',
  path: '/$areaId',
  getParentRoute: () => PosPreparationRoute,
} as any)
const LoyaltyQrTokenRoute = LoyaltyQrTokenRouteImport.update({
  id: '/qr/$token',
  path: '/qr/$token',
  getParentRoute: () => LoyaltyRoute,
} as any)
const GuestMerchantSlugRoute = GuestMerchantSlugRouteImport.update({
  id: '/guest/merchant/$slug',
  path: '/guest/merchant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerMerchantSlugRoute = CustomerMerchantSlugRouteImport.update({
  id: '/customer/merchant/$slug',
  path: '/customer/merchant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMerchantSignupRoute = AuthMerchantSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthMerchantRoute,
} as any)
const AuthMerchantLoginRoute = AuthMerchantLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthMerchantRoute,
} as any)
const MSlugTableTokenRoute = MSlugTableTokenRouteImport.update({
  id: '/table/$token',
  path: '/table/$token',
  getParentRoute: () => MSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cards': typeof CardsRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRouteWithChildren
  '/map': typeof MapRoute
  '/menu': typeof MenuRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/pos': typeof PosRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/merchant': typeof AuthMerchantRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cards/$merchantSlug': typeof CardsMerchantSlugRoute
  '/customer/merchants': typeof CustomerMerchantsRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/merchant/ai': typeof MerchantAiRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/preparation': typeof MerchantPreparationRoute
  '/merchant/specials': typeof MerchantSpecialsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pos/accounts': typeof PosAccountsRoute
  '/pos/cash-movements': typeof PosCashMovementsRoute
  '/pos/conflicts': typeof PosConflictsRoute
  '/pos/orders': typeof PosOrdersRoute
  '/pos/preparation': typeof PosPreparationRouteWithChildren
  '/pos/reports': typeof PosReportsRouteWithChildren
  '/pos/schedule': typeof PosScheduleRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/staff': typeof PosStaffRoute
  '/pos/staff-report': typeof PosStaffReportRoute
  '/stores/$id': typeof StoresIdRoute
  '/merchant/': typeof MerchantIndexRoute
  '/pos/': typeof PosIndexRoute
  '/auth/merchant/login': typeof AuthMerchantLoginRoute
  '/auth/merchant/signup': typeof AuthMerchantSignupRoute
  '/customer/merchant/$slug': typeof CustomerMerchantSlugRoute
  '/guest/merchant/$slug': typeof GuestMerchantSlugRoute
  '/loyalty/qr/$token': typeof LoyaltyQrTokenRoute
  '/pos/preparation/$areaId': typeof PosPreparationAreaIdRoute
  '/pos/reports/z-report': typeof PosReportsZReportRoute
  '/table/$token/order': typeof TableTokenOrderRoute
  '/m/$slug/table/$token': typeof MSlugTableTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cards': typeof CardsRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRouteWithChildren
  '/map': typeof MapRoute
  '/menu': typeof MenuRoute
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/merchant': typeof AuthMerchantRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cards/$merchantSlug': typeof CardsMerchantSlugRoute
  '/customer/merchants': typeof CustomerMerchantsRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/merchant/ai': typeof MerchantAiRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/preparation': typeof MerchantPreparationRoute
  '/merchant/specials': typeof MerchantSpecialsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pos/accounts': typeof PosAccountsRoute
  '/pos/cash-movements': typeof PosCashMovementsRoute
  '/pos/conflicts': typeof PosConflictsRoute
  '/pos/orders': typeof PosOrdersRoute
  '/pos/preparation': typeof PosPreparationRouteWithChildren
  '/pos/reports': typeof PosReportsRouteWithChildren
  '/pos/schedule': typeof PosScheduleRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/staff': typeof PosStaffRoute
  '/pos/staff-report': typeof PosStaffReportRoute
  '/stores/$id': typeof StoresIdRoute
  '/merchant': typeof MerchantIndexRoute
  '/pos': typeof PosIndexRoute
  '/auth/merchant/login': typeof AuthMerchantLoginRoute
  '/auth/merchant/signup': typeof AuthMerchantSignupRoute
  '/customer/merchant/$slug': typeof CustomerMerchantSlugRoute
  '/guest/merchant/$slug': typeof GuestMerchantSlugRoute
  '/loyalty/qr/$token': typeof LoyaltyQrTokenRoute
  '/pos/preparation/$areaId': typeof PosPreparationAreaIdRoute
  '/pos/reports/z-report': typeof PosReportsZReportRoute
  '/table/$token/order': typeof TableTokenOrderRoute
  '/m/$slug/table/$token': typeof MSlugTableTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cards': typeof CardsRouteWithChildren
  '/cart': typeof CartRoute
  '/leaderboard': typeof LeaderboardRoute
  '/loyalty': typeof LoyaltyRouteWithChildren
  '/map': typeof MapRoute
  '/menu': typeof MenuRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/missions': typeof MissionsRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/pos': typeof PosRouteWithChildren
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/stores': typeof StoresRoute
  '/transfers': typeof TransfersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/merchant': typeof AuthMerchantRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/cards/$merchantSlug': typeof CardsMerchantSlugRoute
  '/customer/merchants': typeof CustomerMerchantsRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/orders': typeof CustomerOrdersRoute
  '/m/$slug': typeof MSlugRouteWithChildren
  '/merchant/ai': typeof MerchantAiRoute
  '/merchant/analytics': typeof MerchantAnalyticsRoute
  '/merchant/loyalty': typeof MerchantLoyaltyRoute
  '/merchant/menu': typeof MerchantMenuRoute
  '/merchant/onboarding': typeof MerchantOnboardingRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/preparation': typeof MerchantPreparationRoute
  '/merchant/specials': typeof MerchantSpecialsRoute
  '/merchant/store': typeof MerchantStoreRoute
  '/merchant/tables': typeof MerchantTablesRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pos/accounts': typeof PosAccountsRoute
  '/pos/cash-movements': typeof PosCashMovementsRoute
  '/pos/conflicts': typeof PosConflictsRoute
  '/pos/orders': typeof PosOrdersRoute
  '/pos/preparation': typeof PosPreparationRouteWithChildren
  '/pos/reports': typeof PosReportsRouteWithChildren
  '/pos/schedule': typeof PosScheduleRoute
  '/pos/settings': typeof PosSettingsRoute
  '/pos/staff': typeof PosStaffRoute
  '/pos/staff-report': typeof PosStaffReportRoute
  '/stores_/$id': typeof StoresIdRoute
  '/merchant/': typeof MerchantIndexRoute
  '/pos/': typeof PosIndexRoute
  '/auth/merchant/login': typeof AuthMerchantLoginRoute
  '/auth/merchant/signup': typeof AuthMerchantSignupRoute
  '/customer/merchant/$slug': typeof CustomerMerchantSlugRoute
  '/guest/merchant/$slug': typeof GuestMerchantSlugRoute
  '/loyalty/qr/$token': typeof LoyaltyQrTokenRoute
  '/pos/preparation/$areaId': typeof PosPreparationAreaIdRoute
  '/pos/reports/z-report': typeof PosReportsZReportRoute
  '/table/$token/order': typeof TableTokenOrderRoute
  '/m/$slug/table/$token': typeof MSlugTableTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cards'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/map'
    | '/menu'
    | '/merchant'
    | '/missions'
    | '/notifications'
    | '/offline'
    | '/pos'
    | '/profile'
    | '/rewards'
    | '/stores'
    | '/transfers'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/cards/$merchantSlug'
    | '/customer/merchants'
    | '/customer/order'
    | '/customer/orders'
    | '/m/$slug'
    | '/merchant/ai'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/onboarding'
    | '/merchant/orders'
    | '/merchant/preparation'
    | '/merchant/specials'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/pos/accounts'
    | '/pos/cash-movements'
    | '/pos/conflicts'
    | '/pos/orders'
    | '/pos/preparation'
    | '/pos/reports'
    | '/pos/schedule'
    | '/pos/settings'
    | '/pos/staff'
    | '/pos/staff-report'
    | '/stores/$id'
    | '/merchant/'
    | '/pos/'
    | '/auth/merchant/login'
    | '/auth/merchant/signup'
    | '/customer/merchant/$slug'
    | '/guest/merchant/$slug'
    | '/loyalty/qr/$token'
    | '/pos/preparation/$areaId'
    | '/pos/reports/z-report'
    | '/table/$token/order'
    | '/m/$slug/table/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cards'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/map'
    | '/menu'
    | '/missions'
    | '/notifications'
    | '/offline'
    | '/profile'
    | '/rewards'
    | '/stores'
    | '/transfers'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/cards/$merchantSlug'
    | '/customer/merchants'
    | '/customer/order'
    | '/customer/orders'
    | '/m/$slug'
    | '/merchant/ai'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/onboarding'
    | '/merchant/orders'
    | '/merchant/preparation'
    | '/merchant/specials'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/pos/accounts'
    | '/pos/cash-movements'
    | '/pos/conflicts'
    | '/pos/orders'
    | '/pos/preparation'
    | '/pos/reports'
    | '/pos/schedule'
    | '/pos/settings'
    | '/pos/staff'
    | '/pos/staff-report'
    | '/stores/$id'
    | '/merchant'
    | '/pos'
    | '/auth/merchant/login'
    | '/auth/merchant/signup'
    | '/customer/merchant/$slug'
    | '/guest/merchant/$slug'
    | '/loyalty/qr/$token'
    | '/pos/preparation/$areaId'
    | '/pos/reports/z-report'
    | '/table/$token/order'
    | '/m/$slug/table/$token'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cards'
    | '/cart'
    | '/leaderboard'
    | '/loyalty'
    | '/map'
    | '/menu'
    | '/merchant'
    | '/missions'
    | '/notifications'
    | '/offline'
    | '/pos'
    | '/profile'
    | '/rewards'
    | '/stores'
    | '/transfers'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/merchant'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/cards/$merchantSlug'
    | '/customer/merchants'
    | '/customer/order'
    | '/customer/orders'
    | '/m/$slug'
    | '/merchant/ai'
    | '/merchant/analytics'
    | '/merchant/loyalty'
    | '/merchant/menu'
    | '/merchant/onboarding'
    | '/merchant/orders'
    | '/merchant/preparation'
    | '/merchant/specials'
    | '/merchant/store'
    | '/merchant/tables'
    | '/orders/$id'
    | '/pos/accounts'
    | '/pos/cash-movements'
    | '/pos/conflicts'
    | '/pos/orders'
    | '/pos/preparation'
    | '/pos/reports'
    | '/pos/schedule'
    | '/pos/settings'
    | '/pos/staff'
    | '/pos/staff-report'
    | '/stores_/$id'
    | '/merchant/'
    | '/pos/'
    | '/auth/merchant/login'
    | '/auth/merchant/signup'
    | '/customer/merchant/$slug'
    | '/guest/merchant/$slug'
    | '/loyalty/qr/$token'
    | '/pos/preparation/$areaId'
    | '/pos/reports/z-report'
    | '/table/$token/order'
    | '/m/$slug/table/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CardsRoute: typeof CardsRouteWithChildren
  CartRoute: typeof CartRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoyaltyRoute: typeof LoyaltyRouteWithChildren
  MapRoute: typeof MapRoute
  MenuRoute: typeof MenuRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  MissionsRoute: typeof MissionsRoute
  NotificationsRoute: typeof NotificationsRoute
  OfflineRoute: typeof OfflineRoute
  PosRoute: typeof PosRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  StoresRoute: typeof StoresRoute
  TransfersRoute: typeof TransfersRoute
  CustomerMerchantsRoute: typeof CustomerMerchantsRoute
  CustomerOrderRoute: typeof CustomerOrderRoute
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  MSlugRoute: typeof MSlugRouteWithChildren
  OrdersIdRoute: typeof OrdersIdRoute
  StoresIdRoute: typeof StoresIdRoute
  CustomerMerchantSlugRoute: typeof CustomerMerchantSlugRoute
  GuestMerchantSlugRoute: typeof GuestMerchantSlugRoute
  TableTokenOrderRoute: typeof TableTokenOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/stores_/$id': {
      id: '/stores_/$id'
      path: '/stores/$id'
      fullPath: '/stores/$id'
      preLoaderRoute: typeof StoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/staff-report': {
      id: '/pos/staff-report'
      path: '/staff-report'
      fullPath: '/pos/staff-report'
      preLoaderRoute: typeof PosStaffReportRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/staff': {
      id: '/pos/staff'
      path: '/staff'
      fullPath: '/pos/staff'
      preLoaderRoute: typeof PosStaffRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/settings': {
      id: '/pos/settings'
      path: '/settings'
      fullPath: '/pos/settings'
      preLoaderRoute: typeof PosSettingsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/schedule': {
      id: '/pos/schedule'
      path: '/schedule'
      fullPath: '/pos/schedule'
      preLoaderRoute: typeof PosScheduleRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/reports': {
      id: '/pos/reports'
      path: '/reports'
      fullPath: '/pos/reports'
      preLoaderRoute: typeof PosReportsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/preparation': {
      id: '/pos/preparation'
      path: '/preparation'
      fullPath: '/pos/preparation'
      preLoaderRoute: typeof PosPreparationRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/orders': {
      id: '/pos/orders'
      path: '/orders'
      fullPath: '/pos/orders'
      preLoaderRoute: typeof PosOrdersRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/conflicts': {
      id: '/pos/conflicts'
      path: '/conflicts'
      fullPath: '/pos/conflicts'
      preLoaderRoute: typeof PosConflictsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/cash-movements': {
      id: '/pos/cash-movements'
      path: '/cash-movements'
      fullPath: '/pos/cash-movements'
      preLoaderRoute: typeof PosCashMovementsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/accounts': {
      id: '/pos/accounts'
      path: '/accounts'
      fullPath: '/pos/accounts'
      preLoaderRoute: typeof PosAccountsRouteImport
      parentRoute: typeof PosRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/tables': {
      id: '/merchant/tables'
      path: '/tables'
      fullPath: '/merchant/tables'
      preLoaderRoute: typeof MerchantTablesRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/store': {
      id: '/merchant/store'
      path: '/store'
      fullPath: '/merchant/store'
      preLoaderRoute: typeof MerchantStoreRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/specials': {
      id: '/merchant/specials'
      path: '/specials'
      fullPath: '/merchant/specials'
      preLoaderRoute: typeof MerchantSpecialsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/preparation': {
      id: '/merchant/preparation'
      path: '/preparation'
      fullPath: '/merchant/preparation'
      preLoaderRoute: typeof MerchantPreparationRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/onboarding': {
      id: '/merchant/onboarding'
      path: '/onboarding'
      fullPath: '/merchant/onboarding'
      preLoaderRoute: typeof MerchantOnboardingRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/menu': {
      id: '/merchant/menu'
      path: '/menu'
      fullPath: '/merchant/menu'
      preLoaderRoute: typeof MerchantMenuRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/loyalty': {
      id: '/merchant/loyalty'
      path: '/loyalty'
      fullPath: '/merchant/loyalty'
      preLoaderRoute: typeof MerchantLoyaltyRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/analytics': {
      id: '/merchant/analytics'
      path: '/analytics'
      fullPath: '/merchant/analytics'
      preLoaderRoute: typeof MerchantAnalyticsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/ai': {
      id: '/merchant/ai'
      path: '/ai'
      fullPath: '/merchant/ai'
      preLoaderRoute: typeof MerchantAiRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/order': {
      id: '/customer/order'
      path: '/customer/order'
      fullPath: '/customer/order'
      preLoaderRoute: typeof CustomerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/merchants': {
      id: '/customer/merchants'
      path: '/customer/merchants'
      fullPath: '/customer/merchants'
      preLoaderRoute: typeof CustomerMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$merchantSlug': {
      id: '/cards/$merchantSlug'
      path: '/$merchantSlug'
      fullPath: '/cards/$merchantSlug'
      preLoaderRoute: typeof CardsMerchantSlugRouteImport
      parentRoute: typeof CardsRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/merchant': {
      id: '/auth/merchant'
      path: '/merchant'
      fullPath: '/auth/merchant'
      preLoaderRoute: typeof AuthMerchantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/table/$token/order': {
      id: '/table/$token/order'
      path: '/table/$token/order'
      fullPath: '/table/$token/order'
      preLoaderRoute: typeof TableTokenOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/reports/z-report': {
      id: '/pos/reports/z-report'
      path: '/z-report'
      fullPath: '/pos/reports/z-report'
      preLoaderRoute: typeof PosReportsZReportRouteImport
      parentRoute: typeof PosReportsRoute
    }
    '/pos/preparation/$areaId': {
      id: '/pos/preparation/$areaId'
      path: '/$areaId'
      fullPath: '/pos/preparation/$areaId'
      preLoaderRoute: typeof PosPreparationAreaIdRouteImport
      parentRoute: typeof PosPreparationRoute
    }
    '/loyalty/qr/$token': {
      id: '/loyalty/qr/$token'
      path: '/qr/$token'
      fullPath: '/loyalty/qr/$token'
      preLoaderRoute: typeof LoyaltyQrTokenRouteImport
      parentRoute: typeof LoyaltyRoute
    }
    '/guest/merchant/$slug': {
      id: '/guest/merchant/$slug'
      path: '/guest/merchant/$slug'
      fullPath: '/guest/merchant/$slug'
      preLoaderRoute: typeof GuestMerchantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/merchant/$slug': {
      id: '/customer/merchant/$slug'
      path: '/customer/merchant/$slug'
      fullPath: '/customer/merchant/$slug'
      preLoaderRoute: typeof CustomerMerchantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/merchant/signup': {
      id: '/auth/merchant/signup'
      path: '/signup'
      fullPath: '/auth/merchant/signup'
      preLoaderRoute: typeof AuthMerchantSignupRouteImport
      parentRoute: typeof AuthMerchantRoute
    }
    '/auth/merchant/login': {
      id: '/auth/merchant/login'
      path: '/login'
      fullPath: '/auth/merchant/login'
      preLoaderRoute: typeof AuthMerchantLoginRouteImport
      parentRoute: typeof AuthMerchantRoute
    }
    '/m/$slug/table/$token': {
      id: '/m/$slug/table/$token'
      path: '/table/$token'
      fullPath: '/m/$slug/table/$token'
      preLoaderRoute: typeof MSlugTableTokenRouteImport
      parentRoute: typeof MSlugRoute
    }
  }
}

interface AuthMerchantRouteChildren {
  AuthMerchantLoginRoute: typeof AuthMerchantLoginRoute
  AuthMerchantSignupRoute: typeof AuthMerchantSignupRoute
}

const AuthMerchantRouteChildren: AuthMerchantRouteChildren = {
  AuthMerchantLoginRoute: AuthMerchantLoginRoute,
  AuthMerchantSignupRoute: AuthMerchantSignupRoute,
}

const AuthMerchantRouteWithChildren = AuthMerchantRoute._addFileChildren(
  AuthMerchantRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMerchantRoute: typeof AuthMerchantRouteWithChildren
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMerchantRoute: AuthMerchantRouteWithChildren,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CardsRouteChildren {
  CardsMerchantSlugRoute: typeof CardsMerchantSlugRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsMerchantSlugRoute: CardsMerchantSlugRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface LoyaltyRouteChildren {
  LoyaltyQrTokenRoute: typeof LoyaltyQrTokenRoute
}

const LoyaltyRouteChildren: LoyaltyRouteChildren = {
  LoyaltyQrTokenRoute: LoyaltyQrTokenRoute,
}

const LoyaltyRouteWithChildren =
  LoyaltyRoute._addFileChildren(LoyaltyRouteChildren)

interface MerchantRouteChildren {
  MerchantAiRoute: typeof MerchantAiRoute
  MerchantAnalyticsRoute: typeof MerchantAnalyticsRoute
  MerchantLoyaltyRoute: typeof MerchantLoyaltyRoute
  MerchantMenuRoute: typeof MerchantMenuRoute
  MerchantOnboardingRoute: typeof MerchantOnboardingRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantPreparationRoute: typeof MerchantPreparationRoute
  MerchantSpecialsRoute: typeof MerchantSpecialsRoute
  MerchantStoreRoute: typeof MerchantStoreRoute
  MerchantTablesRoute: typeof MerchantTablesRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantAiRoute: MerchantAiRoute,
  MerchantAnalyticsRoute: MerchantAnalyticsRoute,
  MerchantLoyaltyRoute: MerchantLoyaltyRoute,
  MerchantMenuRoute: MerchantMenuRoute,
  MerchantOnboardingRoute: MerchantOnboardingRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantPreparationRoute: MerchantPreparationRoute,
  MerchantSpecialsRoute: MerchantSpecialsRoute,
  MerchantStoreRoute: MerchantStoreRoute,
  MerchantTablesRoute: MerchantTablesRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

interface PosPreparationRouteChildren {
  PosPreparationAreaIdRoute: typeof PosPreparationAreaIdRoute
}

const PosPreparationRouteChildren: PosPreparationRouteChildren = {
  PosPreparationAreaIdRoute: PosPreparationAreaIdRoute,
}

const PosPreparationRouteWithChildren = PosPreparationRoute._addFileChildren(
  PosPreparationRouteChildren,
)

interface PosReportsRouteChildren {
  PosReportsZReportRoute: typeof PosReportsZReportRoute
}

const PosReportsRouteChildren: PosReportsRouteChildren = {
  PosReportsZReportRoute: PosReportsZReportRoute,
}

const PosReportsRouteWithChildren = PosReportsRoute._addFileChildren(
  PosReportsRouteChildren,
)

interface PosRouteChildren {
  PosAccountsRoute: typeof PosAccountsRoute
  PosCashMovementsRoute: typeof PosCashMovementsRoute
  PosConflictsRoute: typeof PosConflictsRoute
  PosOrdersRoute: typeof PosOrdersRoute
  PosPreparationRoute: typeof PosPreparationRouteWithChildren
  PosReportsRoute: typeof PosReportsRouteWithChildren
  PosScheduleRoute: typeof PosScheduleRoute
  PosSettingsRoute: typeof PosSettingsRoute
  PosStaffRoute: typeof PosStaffRoute
  PosStaffReportRoute: typeof PosStaffReportRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosAccountsRoute: PosAccountsRoute,
  PosCashMovementsRoute: PosCashMovementsRoute,
  PosConflictsRoute: PosConflictsRoute,
  PosOrdersRoute: PosOrdersRoute,
  PosPreparationRoute: PosPreparationRouteWithChildren,
  PosReportsRoute: PosReportsRouteWithChildren,
  PosScheduleRoute: PosScheduleRoute,
  PosSettingsRoute: PosSettingsRoute,
  PosStaffRoute: PosStaffRoute,
  PosStaffReportRoute: PosStaffReportRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

interface MSlugRouteChildren {
  MSlugTableTokenRoute: typeof MSlugTableTokenRoute
}

const MSlugRouteChildren: MSlugRouteChildren = {
  MSlugTableTokenRoute: MSlugTableTokenRoute,
}

const MSlugRouteWithChildren = MSlugRoute._addFileChildren(MSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CardsRoute: CardsRouteWithChildren,
  CartRoute: CartRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoyaltyRoute: LoyaltyRouteWithChildren,
  MapRoute: MapRoute,
  MenuRoute: MenuRoute,
  MerchantRoute: MerchantRouteWithChildren,
  MissionsRoute: MissionsRoute,
  NotificationsRoute: NotificationsRoute,
  OfflineRoute: OfflineRoute,
  PosRoute: PosRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  StoresRoute: StoresRoute,
  TransfersRoute: TransfersRoute,
  CustomerMerchantsRoute: CustomerMerchantsRoute,
  CustomerOrderRoute: CustomerOrderRoute,
  CustomerOrdersRoute: CustomerOrdersRoute,
  MSlugRoute: MSlugRouteWithChildren,
  OrdersIdRoute: OrdersIdRoute,
  StoresIdRoute: StoresIdRoute,
  CustomerMerchantSlugRoute: CustomerMerchantSlugRoute,
  GuestMerchantSlugRoute: GuestMerchantSlugRoute,
  TableTokenOrderRoute: TableTokenOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
