// src/features/inventory/copy.ts
// Every user-facing inventory string lives here so the feature can be
// translated (e.g. to Nepali) without touching components. Keep the English
// short, plain and free of accounting jargon.

export const copy = {
  common: {
    cancel: "Cancel",
    close: "Close",
    back: "Back",
    save: "Save",
    saving: "Saving…",
    saved: "Saved",
    done: "Done",
    tryAgain: "Try again",
    optional: "optional",
    search: "Search",
    loading: "Loading…",
    next: "Next",
    previous: "Previous",
    edit: "Edit",
    delete: "Delete",
    all: "All",
    everything: "Everything",
    notSaved: "Not saved",
    showMore: "Show more",
    pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
    noPermission: "You don't have permission to do this. Ask a manager.",
  },

  nav: {
    title: "Inventory",
    overview: "Overview",
    stock: "Stock",
    count: "Count Stock",
    actions: "Add / Move Stock",
    suppliers: "Suppliers",
    reports: "Reports",
    history: "History",
    importExport: "Import / Export",
    settings: "Settings",
  },

  home: {
    greeting: (name: string) => {
      const hour = new Date().getHours();
      const part = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";
      return name ? `${part}, ${name}.` : `${part}.`;
    },
    question: "What do you want to do?",
    checkStock: "Check Stock",
    checkStockHint: "See what is available now",
    countStock: "Count Stock",
    countStockHint: "Count what is physically there",
    addDelivery: "Add Delivery",
    addDeliveryHint: "New stock arrived",
    moveStock: "Move Stock",
    moveStockHint: "Move stock between places",
    recordWaste: "Record Waste",
    recordWasteHint: "Something spoiled, broke or was lost",
    needsAttention: "Needs Attention",
    allGood: "Everything looks good.",
    allGoodHint: "No items need attention right now.",
    seeAllLow: (n: number) => `See all ${n} items`,
    managerTools: "Manager Tools",
    waitingReview: (n: number) => `${n} stock count${n === 1 ? "" : "s"} waiting for review`,
    correctionsWaiting: (n: number) => `${n} stock fix${n === 1 ? "" : "es"} waiting for approval`,
    left: (qty: string, unit: string) => `${qty} ${unit} left`,
    emptyTitle: "No stock items yet.",
    emptyHint: "Add your first item or import your inventory.",
  },

  status: {
    HEALTHY: "Good",
    LOW: "Low",
    CRITICAL: "Very Low",
    OUT: "Out",
    OVERSTOCK: "More Than Usual",
  } as Record<string, string>,

  itemType: {
    INGREDIENT: "Food / Ingredient",
    PREPARED: "Prepared Here",
    DIRECT_SALE: "Drink / Sold As-Is",
    SUPPLY: "Packaging / Supply",
  } as Record<string, string>,

  itemTypeHint: {
    INGREDIENT: "Raw food you cook with",
    PREPARED: "Sauces, dough, prep you make",
    DIRECT_SALE: "Bottles, cans, snacks you sell",
    SUPPLY: "Cups, boxes, napkins, cleaning",
  } as Record<string, string>,

  stock: {
    title: "Stock",
    itemCol: "Item",
    actionsCol: "Actions",
    searchPlaceholder: "Search stock…",
    addItem: "Add Stock Item",
    importInventory: "Import Inventory",
    allLocations: "All places",
    allCategories: "All categories",
    left: "left",
    noResults: "No stock matches your search.",
    noResultsHint: "Try another word or clear the filters.",
    clearFilters: "Clear filters",
    items: (n: number) => `${n} stock item${n === 1 ? "" : "s"}`,
    at: (place: string) => `at ${place}`,
  },

  detail: {
    currentStock: "Current Stock",
    usuallyKeptIn: "Usually Kept In",
    status: "Status",
    lastCounted: "Last Counted",
    lastDelivery: "Last Delivery",
    whereItIs: "Where it is now",
    never: "Never",
    count: "Count",
    addDelivery: "Add Delivery",
    move: "Move",
    recordWaste: "Record Waste",
    editItem: "Edit Item",
    fixStock: "Fix Stock",
    viewHistory: "View History",
    deleteItem: "Delete Item",
    more: "More details",
    keepAround: "Keep Around",
    warnMeBelow: "Warn Me Below",
    veryLowLevel: "Very Low Level",
    howYouBuy: "How You Buy It",
    code: "SKU / Code",
    barcode: "Barcode",
    category: "Category",
    supplier: "Supplier",
    stockValue: "Stock Value",
    averageCost: "Average Cost",
    recentChanges: "Recent changes",
  },

  deleteItem: {
    title: (name: string) => `Delete ${name}?`,
    noHistory: "This item has no stock history, so it will be removed completely.",
    withHistory:
      "This item will be removed from your lists. Its stock history stays, so past reports remain correct.",
    stockLeft: (qty: string, unit: string) =>
      `It still has ${qty} ${unit} in stock. Deleting it will also remove that stock with a recorded fix.`,
    confirm: "Delete Item",
    confirmWithStock: "Remove Stock and Delete",
    deleted: (name: string) => `${name} deleted.`,
    archived: (name: string) => `${name} removed. Its history is kept.`,
  },

  itemForm: {
    addTitle: "Add Stock Item",
    editTitle: "Edit Stock Item",
    editHint: "Change the details. To change how much you have, use Count Stock or Fix Stock.",
    q1: "What is it called?",
    q1Placeholder: "e.g. Chicken Breast",
    q2: "What kind of item is it?",
    q3: "How do you count it?",
    q3Hint: "Choose the unit you use when you count it.",
    q4: "Where is it usually stored?",
    q5: "How much do you have now?",
    q5Hint: "Leave empty if you have none yet.",
    advanced: "Advanced",
    advancedHint: "Category, codes, stock alerts, buying and menu links",
    category: "Category",
    sku: "SKU / Item code",
    barcode: "Barcode",
    displayUnit: "Preferred display unit",
    alerts: "Stock Alerts",
    keepAround: "Keep Around",
    keepAroundHint: "Try to keep about this much in stock.",
    warnMeBelow: "Warn Me Below",
    warnMeBelowHint: "Show this item as Low below this amount.",
    veryLow: "Very Low Level",
    veryLowHint: "Show this item as Very Low below this amount.",
    buying: "Buying & Supplier",
    howBuy: "How do you buy this item?",
    sameAsCount: "Same way I count it",
    inPacks: "In bags / boxes / cases",
    buyAs: "I buy it as",
    buyAsPlaceholder: "e.g. Sack",
    oneContains: (label: string) => `One ${label || "pack"} contains`,
    packSummary: (label: string, qty: string, unit: string) => `1 ${label} = ${qty} ${unit}`,
    startingCost: "What did it cost per unit?",
    supplier: "Usual supplier",
    noSupplier: "No usual supplier",
    menuLinks: "Use up when sold",
    menuLinksHint: "Dine-in orders for these menu items take stock from this item.",
    linkMenuItem: "Link a menu item",
    menuItem: "Menu item",
    perSale: "Used per sale",
    submitAdd: "Add Item",
    submitEdit: "Save Changes",
    added: (name: string) => `${name} added.`,
    saved: (name: string) => `${name} saved.`,
    duplicate: (name: string) => `A stock item called “${name}” already exists.`,
    openExisting: "Open Existing",
    addAnyway: "Add Anyway",
    choose: "Choose…",
    needName: "Give the item a name.",
    needUnit: "Choose how you count it.",
    needLocation: "Choose where it is stored so the starting stock has a place.",
  },

  actions: {
    title: "Add / Move Stock",
    subtitle: "What happened?",
    addDelivery: "Add Delivery",
    addDeliveryHint: "New stock arrived from a supplier or market.",
    moveStock: "Move Stock",
    moveStockHint: "Move stock from one place to another.",
    recordWaste: "Record Waste",
    recordWasteHint: "Something spoiled, broke, expired or was thrown away.",
    fixStock: "Fix Stock",
    fixStockHint: "The number is wrong. Correct it (manager only).",
    waitingFixes: "Stock fixes waiting for approval",
    approve: "Approve",
    reject: "Reject",
  },

  delivery: {
    title: "New Delivery",
    where: "Where did it arrive?",
    who: "Who delivered it?",
    noSupplier: "Not from a saved supplier",
    reference: "Reference / invoice",
    whatArrived: "What arrived?",
    item: "Item",
    howMany: "How many?",
    cost: "Cost",
    costHint: "Price per",
    addAnother: "Add Another Item",
    remove: "Remove",
    submit: "Add to Stock",
    confirmTitle: "Add this delivery to stock?",
    successTitle: "Delivery Added",
    newStock: "New stock",
    addAnotherDelivery: "Add Another Delivery",
    failed: "Delivery was not added. Your stock has not changed.",
    toast: (qty: string, unit: string, item: string) =>
      `Delivery added. ${item} is now ${qty} ${unit}.`,
    needItem: "Choose what arrived and how much.",
  },

  move: {
    title: "Move Stock",
    from: "Move from",
    to: "Move to",
    what: "What are you moving?",
    howMuch: "How much?",
    available: (qty: string, unit: string) => `${qty} ${unit} there now`,
    note: "Note",
    submit: "Move Stock",
    confirmTitle: "Move this stock now?",
    successTitle: "Stock Moved",
    moveAnother: "Move Something Else",
    failed: "Stock was not moved. Nothing has changed.",
    samePlace: "Choose two different places.",
    toast: (qty: string, unit: string, item: string, to: string) =>
      `${qty} ${unit} ${item} moved to ${to}.`,
    statuses: {
      DRAFT: "Not Started",
      REQUESTED: "Not Started",
      APPROVED: "Not Started",
      IN_TRANSIT: "Being Moved",
      RECEIVED: "Moved",
      CANCELLED: "Cancelled",
    } as Record<string, string>,
    earlierMoves: "Moves waiting to finish",
    finish: "Finish Move",
  },

  waste: {
    title: "Record Waste",
    what: "What was wasted?",
    howMuch: "How much?",
    where: "Where?",
    why: "Why?",
    otherReason: "What happened?",
    note: "Note",
    submit: "Record Waste",
    confirmTitle: "Record this waste?",
    confirmBody: "This removes the stock now. It shows in waste reports.",
    successTitle: "Waste Recorded",
    recordMore: "Record More Waste",
    failed: "Waste was not recorded. Your stock has not changed.",
    toast: (qty: string, unit: string, item: string) => `Waste recorded: ${qty} ${unit} ${item}.`,
    reasons: {
      SPOILED: "Spoiled",
      EXPIRED: "Expired",
      DROPPED: "Dropped",
      DAMAGED: "Damaged",
      OVER_PREPARED: "Over-prepared",
      KITCHEN_MISTAKE: "Kitchen mistake",
      CUSTOMER_RETURN: "Customer return",
      STAFF_MEAL: "Staff meal",
      OTHER: "Other",
    } as Record<string, string>,
  },

  fix: {
    title: "Fix Stock",
    item: "Item",
    where: "Where?",
    current: "Current stock here",
    change: "What needs to change?",
    add: "Add Stock",
    remove: "Remove Stock",
    amount: "Amount",
    why: "Why?",
    note: "Note",
    reasons: [
      "Data entry mistake",
      "Found extra stock",
      "Stock missing",
      "Delivery was entered wrong",
      "Other",
    ],
    submit: "Update Stock",
    confirmTitle: "Update stock?",
    willBecome: (qty: string, unit: string) => `Stock here will become ${qty} ${unit}.`,
    needsApproval: "The owner will approve this before stock changes.",
    successTitle: "Stock Updated",
    pendingTitle: "Sent for Approval",
    pendingBody: "Stock will change after the owner approves it.",
    fixAnother: "Fix Something Else",
    failed: "Stock was not updated. Nothing has changed.",
    toast: (qty: string, unit: string, item: string) =>
      `Stock updated. ${item} is now ${qty} ${unit}.`,
  },

  count: {
    title: "Count Stock",
    where: "Where are you counting?",
    everything: "Everything",
    everythingHint: "All places",
    continueTitle: "Continue counting",
    waitingTitle: "Waiting for review",
    counted: (done: number, total: number) => `${done} of ${total} counted`,
    searchItem: "Search item…",
    systemSays: "System says",
    howMuchSee: "How much do you see?",
    youCounted: "You counted",
    difference: "Difference",
    matches: "Matches",
    less: (qty: string, unit: string) => `${qty} ${unit} less`,
    more: (qty: string, unit: string) => `${qty} ${unit} more`,
    saveLater: "Save & Continue Later",
    finish: "Finish Count",
    finishConfirm: "Finish this count?",
    finishNotAll: (left: number) =>
      `${left} item${left === 1 ? " is" : "s are"} not counted yet. Items you skip keep their current stock.`,
    finished: "Count finished.",
    managerWillReview: "A manager will review the differences before stock is updated.",
    stockUpdated: "Stock has been updated to what you counted.",
    reviewTitle: "Review Count",
    systemSaid: "System said",
    countedCol: "Counted",
    approve: "Approve & Update Stock",
    approveConfirm: "Update stock to the counted amounts?",
    approveBody:
      "Every counted item will be set to what was counted. This is saved in Stock History.",
    approved: "Stock updated from the count.",
    cancelCount: "Cancel Count",
    cancelConfirm: "Cancel this count? Nothing you entered will change stock.",
    nothingHere: "There are no stock items in this place yet.",
    notCounted: "Not counted",
    onlyDifferences: "Only show differences",
    hideCounted: "Hide counted",
    started: (by: string) => (by ? `Started by ${by}` : "Started"),
    newCount: "Start a New Count",
    noItemsCounted: "Count at least one item before finishing.",
    savedTick: "Saved",
  },

  history: {
    title: "Stock History",
    subtitle: "Every change to your stock, and who made it.",
    filters: {
      all: "All",
      deliveries: "Deliveries",
      counts: "Counts",
      waste: "Waste",
      moves: "Moves",
      corrections: "Corrections",
      sales: "Sales",
      undo: "Undo",
    } as Record<string, string>,
    by: (name: string) => (name ? `by ${name}` : ""),
    approvedBy: (name: string) => `Approved by ${name}`,
    undo: "Undo This Change",
    undone: "Undone",
    undoTitle: "Undo this change?",
    undoBody:
      "This will create an opposite stock entry. The original record will remain in Stock History.",
    undoConfirm: "Undo Change",
    undoToast: "Change undone. Stock history updated.",
    empty: "No stock changes yet.",
    today: "Today",
    yesterday: "Yesterday",
    loadMore: "Load more",
  },

  movementLabel: {
    OPENING_BALANCE: "Starting stock",
    RECEIVE: "Delivery added",
    TRANSFER_IN: "Moved in",
    TRANSFER_OUT: "Moved out",
    EXPLICIT_WASTE: "Waste",
    MANUAL_ADJUSTMENT: "Stock fixed",
    COUNT_RECONCILIATION: "Stock count",
    RETURN_TO_SUPPLIER: "Returned to supplier",
    REVERSAL: "Undo",
    SALE: "Sold",
  } as Record<string, string>,

  reports: {
    title: "Reports",
    subtitle: "Pick a report, filter it, then download it.",
    names: {
      "current-stock": "Current Stock",
      "low-stock": "Low Stock",
      "stock-history": "Stock Movements",
      "stock-counts": "Stock Counts",
      "count-differences": "Count Differences",
      waste: "Waste",
      purchasing: "Purchasing",
      deliveries: "Deliveries",
    } as Record<string, string>,
    hints: {
      "current-stock": "How much of everything you have, by place.",
      "low-stock": "Items that are low, very low or out.",
      "stock-history": "Every stock change in a date range.",
      "stock-counts": "Counts that were done and who did them.",
      "count-differences": "Where counted stock differed from the system.",
      waste: "What was wasted and why.",
      purchasing: "Orders placed with suppliers.",
      deliveries: "Deliveries that were added.",
    } as Record<string, string>,
    from: "From",
    to: "To",
    location: "Place",
    category: "Category",
    downloadCsv: "Download CSV",
    downloadPdf: "Download PDF",
    csvHint: "For spreadsheets",
    pdfHint: "For printing and sharing",
    downloading: "Preparing file…",
    downloaded: "Download started.",
    noRows: "Nothing to show for these filters.",
    rows: (n: number) => `${n} row${n === 1 ? "" : "s"}`,
  },

  importExport: {
    title: "Import & Export",
    importHeading: "Import",
    importCsv: "Import Inventory CSV",
    importCsvHint: "From a spreadsheet saved as CSV",
    importPdf: "Import Inventory PDF",
    importPdfHint: "From an old stock sheet. You review everything first.",
    templates: "Templates",
    csvTemplate: "Download CSV Template",
    csvExample: "Download Example File",
    countTemplate: "Download Count Template",
    exportHeading: "Export",
    exportStock: "Export Current Stock CSV",
    downloadPdf: "Download Inventory PDF",
    exportHistory: "Export Stock History",
    exportWaste: "Export Waste",
    exportCounts: "Export Stock Counts",
    recent: "Recent imports",
  },

  importWizard: {
    titleCsv: "Import Inventory",
    titlePdf: "Import from PDF",
    step1: "What are you importing?",
    modes: {
      NEW_ITEMS: "New Stock Items",
      UPDATE_ITEMS: "Update Item Details",
      STOCK_COUNT: "Physical Stock Count",
    } as Record<string, string>,
    modeHints: {
      NEW_ITEMS: "Create item definitions. Starting quantity is added only for new items.",
      UPDATE_ITEMS:
        "Update names, categories, alerts and buying details. Stock quantities are not changed.",
      STOCK_COUNT:
        "Import counted quantities as a count draft. A manager reviews and approves before stock changes.",
    } as Record<string, string>,
    fallbackLocation: "If a row has no place, use",
    noFallback: "Each row says its place",
    chooseFile: "Choose File",
    fileTypesCsv: "CSV file, up to 5 MB",
    fileTypesPdf: "PDF file, up to 10 MB",
    reading: "Reading and checking your file…",
    readingPdf: "Reading your PDF… scanned files can take up to a minute.",
    found: (n: number) => `${n} row${n === 1 ? "" : "s"} found`,
    foundPdf: (n: number) => `Zentro found ${n} stock line${n === 1 ? "" : "s"}`,
    ready: (n: number) => `${n} ready`,
    warnings: (n: number) => `${n} warning${n === 1 ? "" : "s"}`,
    errors: (n: number) => `${n} error${n === 1 ? "" : "s"}`,
    highConfidence: (n: number) => `${n} high confidence`,
    needReview: (n: number) => `${n} need review`,
    unreadable: (n: number) => `${n} could not be read`,
    filters: { all: "All", problems: "Problems", ready: "Ready", skip: "Skipped" } as Record<
      string,
      string
    >,
    row: (n: number) => `Row ${n}`,
    line: (n: number) => `Line ${n}`,
    statusLabel: {
      ready: "Ready",
      warning: "Check",
      error: "Needs fixing",
      skip: "Will skip",
    } as Record<string, string>,
    possibleMatch: "Possible match",
    updateExisting: "Update Existing",
    createNew: "Create New",
    skip: "Skip",
    include: "Include",
    confirm: "Confirm",
    confirmed: "Confirmed",
    zentroRead: "Zentro read",
    originalText: "Original text",
    editRow: "Fix",
    applyFix: "Check Again",
    systemSays: "System says",
    imported: "Imported count",
    downloadErrors: "Download Error Report",
    fixFile: "Upload a Different File",
    importN: (n: number) => `Import ${n} Ready Item${n === 1 ? "" : "s"}`,
    createCountN: (n: number) => `Create Count Draft (${n} item${n === 1 ? "" : "s"})`,
    bulkConfirmTitle: (n: number) => `Import ${n} rows?`,
    bulkConfirmBody: "Rows with errors or not confirmed will be skipped.",
    duplicateTitle: "This file appears to have already been imported.",
    viewPrevious: "View Previous Import",
    importAgain: "Import Again Anyway",
    importing: "Importing… please keep this page open.",
    doneTitle: "Inventory Import Complete",
    countDoneTitle: "Count Draft Created",
    doneImported: (n: number) => `${n} imported`,
    doneSkipped: (n: number) => `${n} skipped`,
    doneFailed: (n: number) => `${n} failed`,
    openingAdded: (n: number) => `Starting stock added: ${n} item${n === 1 ? "" : "s"}`,
    noOverwrite: "No existing stock was overwritten.",
    countNext: "Open Count Stock to review the differences and approve them.",
    viewStock: "View Stock",
    reviewCount: "Review Count",
    downloadResult: "Download Result CSV",
    cancelImport: "Cancel Import",
  },

  settings: {
    title: "Settings",
    safety: "Stock Safety",
    countApproval: "Manager approves stock counts",
    countApprovalHint: "Counted amounts update stock only after a manager approves them.",
    negativeStock: "Prevent stock below zero",
    negativeStockHint: "Stop any action that would make stock go below zero.",
    fixApproval: "Owner approves stock fixes",
    fixApprovalHint: "Fixes made by managers wait for the owner before stock changes.",
    places: "Places",
    placesHint: "Where you keep stock.",
    categories: "Categories",
    categoriesHint: "Groups for your stock items.",
    addPlace: "Add place",
    addCategory: "Add category",
    rename: "Rename",
    hidden: "Hidden (still used by old records)",
    audit: "Audit History",
    auditHint: "Sensitive actions, newest first.",
  },

  staff: {
    staffMode: "Staff Mode",
    start: "Hand to Staff",
    startHint: "Staff see only what their role allows.",
    who: "Who is using this device?",
    pin: "PIN",
    enter: "Start",
    banner: (name: string) => `Staff mode · ${name}`,
    exit: "Exit Staff Mode",
    exitTitle: "Exit staff mode",
    exitHint: "Enter the owner password, or a manager PIN.",
    ownerPassword: "Owner password",
    orManager: "Or a manager",
    managerPin: "Manager PIN",
    exitButton: "Exit",
    ended: "Staff session ended. Please sign in again.",
    noWorkers: "No staff yet. Add staff in POS settings to use staff mode.",
  },

  suppliers: {
    title: "Suppliers",
    orders: "Orders From Suppliers",
    newSupplier: "New Supplier",
    newOrder: "New Supplier Order",
  },

  errors: {
    load: "Could not load this. Check your connection and try again.",
    generic: "Something went wrong. Please try again.",
  },
};

export type Copy = typeof copy;
